aptos-labs/developer-docs

docs/tutorials/build-e2e-dapp/3-add-wallet-support.md, docs/tutorials/build-e2e-dapp/4-fetch-data-from-chain.md, docs/tutorials/build-e2e-dapp/5-submit-data-to-chain.md, docs/tutorials/build-e2e-dapp/6-handle-tasks.md, docs/tutorials/build-e2e-dapp/index.md
Update build e2e dapp tutorial with new adapter and sdk. 
PR to update the tutorial code is also out https://github.com/aptos-labs/aptos-core/pull/11280
=> Update e2e dapp tutorial with new tool versions

docs/move/book/unit-testing.md, docs/tutorials/build-e2e-dapp/5-submit-data-to-chain.md, docs/tutorials/build-e2e-dapp/index.md
Clarify description of expected_error annotations.
Fixes #8905.
=> correct documentation of expected_attribute

docs/tutorials/first-fungible-asset.md
Copying changes from the old code on aptos-core repo https://github.com/aptos-labs/aptos-core/pull/11261
=> update first fungible asset example to use the new sdk

docs/nodes/validator-node/operator/delegation-pool-operations.md, docs/nodes/validator-node/operator/staking-pool-operations.md
Added the doc for changing beneficiary addresses
`pnpm lint` and `pnpm fmt` passed.
=> [staking] Added the doc for changing beneficiary addresses

src/components/MoveReference/index.tsx
=> [move-reference] Fix branch selector

package.json, pnpm-lock.yaml
This overrides an old version of semver to fix issues with the old version.
=> [deps] Override semver package

docusaurus.config.js
=> [docusaurus] Fix edit url

docs/sdks/new-ts-sdk/index.md, docs/sdks/new-ts-sdk/transaction-builder.md
=> Fix new sdk docs

docs/CODEOWNERS
=> Add banool to CODEOWNERS for indexer docs

static/sdks/typescript/examples/typescript-esm/package.json, static/sdks/typescript/examples/typescript-esm/pnpm-lock.yaml, static/sdks/typescript/examples/typescript/package.json, static/sdks/typescript/examples/typescript/pnpm-lock.yaml
=> [examples] Update dependencies in typescript examples

docs/move/book/loops.md, docs/tutorials/programmatic-upgradeable-module.md
Update move book to include for loops
=> add documentation for for loop

docs/tutorials/build-e2e-dapp/6-handle-tasks.md
Thanks for this useful tutorial. I found some errors that prevented me from completing it. The description of the changes is in the description section. Thanks.
Use the defined variable name(starts with lowercase) and remove the **data** field(which does not exist) to access **tasks** and **task_counter** of the **todoListResource**.
=> fix todoListResource errors

docs/nodes/nodes-landing.md
For some reason these links are custom HTML.  I've hardcoded the absolute links now, since they were confusing as relative links. We should think about not making custom HTML for these pages when possible.
=> [nodes] Fix node landing links

docs/community/aptos-style.md, docs/community/site-updates.md, docs/concepts/base-gas.md, docs/move/prover/supporting-resources.md, src/contributors.json
I did a quick web URL deadlink check, along with some other cleanups around links
=> [links] Link cleanup

docs/concepts/governance.md, scripts/additional_dict.txt, src/components/MoveReference/index.tsx
Note, this is more legible in dark mode, but is still visible in light mode.  Will need someone with more frontend experience to fix it later.
=> [mermaid] Change to dark mode by default

docs/guides/local-development-network.md
=> Update local development guide to use TS SDK v2

docs/guides/sponsored-transactions.md
=> Add TS SDK sponsor transaction example link

docs/nodes/validator-node/operator/node-requirements.md
=> Update hardware requirement in mainnet for 30k TPS

docs/indexer/api/self-hosted.md
https://aptos-org.slack.com/archives/C04PRP1K1FZ/p1706241063942309
=> [Indexer API] Add note about configuration when running using Docker Desktop

docs/sdks/rust-sdk.md
=> Add x25519-dalek fix to sample Cargo.toml in rust sdk instructions

docs/nodes/validator-node/operator/delegation-pool-operations.md
* Added the instruction for the new feature of changing commission rates in delegation pools
* Added the missing instruction for updating delegated voters in delegation pools
=> Documentation for the operation to change commission rates in delegation pools

docs/sdks/new-ts-sdk/index.md, docs/sdks/new-ts-sdk/transaction-builder.md
=> Update TS SDK transaction submission syntax

docs/sdks/index.md
=> Change Typescript SDK to point to new SDK

docs/reference/glossary.md
=> Glossary changes: Accounts, Blocks, Shoal, Version

docs/move/move-on-aptos/move-security-guidelines.md, docs/tutorials/your-first-nft.md
Double title removed in Move Sec. Guidelines
=> double title removed, pnpm fmt

docs/move/move-on-aptos/objects/configuring-objects.md, docs/move/move-on-aptos/objects/creating-objects.md, docs/move/move-on-aptos/objects/index.md
=> [objects] Reword some pieces of the objects doc

apps/nextra/docs.config.js, apps/nextra/pages/en/docs/setup/docs-config.mdx, apps/nextra/theme.config.tsx
=> [nextra] Fix Nextra Github Urls

apps/docusaurus/docs/guides/keyless-accounts.md
Adding localStorage code examples to keyless-accounts guide.
=> [docusaurus] Add collapsible localStorage examples to keyless-accounts

apps/docusaurus/docs/guides/keyless-accounts.md, apps/docusaurus/scripts/additional_dict.txt
=> Add keyless integration guide

apps/docusaurus/docs/index.md
=> Add banner for new dev discussion

apps/docusaurus/docs/index.md, apps/docusaurus/docs/nodes/validator-node/operator/staking-pool-operations.md
=> [landing-page] Fix getting started link

apps/docusaurus/docs/tutorials/first-coin.md, apps/docusaurus/docs/tutorials/first-fungible-asset.md, apps/docusaurus/docs/tutorials/first-transaction.md, apps/docusaurus/docs/tutorials/your-first-nft.md
=> fix ts-sdk inscutrions in tutorials

apps/docusaurus/scripts/additional_dict.txt
=> add a few words to the dictionary

apps/docusaurus/docs/nodes/operations/index.md
it confused operators
- [] Do all Lints pass? -- how?
- [] Have you ran `pnpm spellcheck`? -- irrelevant failure
=> clarify non-fast-sync way of bootstrapping node is optional

apps/docusaurus/docs/nodes/full-node/aptos-db-restore.md
=> update db restore doc

apps/docusaurus/docs/guides/keyless-accounts.md
Update verbiage to use key pair.
=> Fix Keyless docs 

apps/nextra/README.md, apps/nextra/theme.config.tsx
=> [nextra] Clearer env variable missing error, better README.md

apps/docusaurus/docs/concepts/move.md
=> chore: fix typo of AIP-11 link

apps/docusaurus/docs/guides/keyless-accounts.md
=> Update variable name in keyless doc

apps/docusaurus/docusaurus.config.ts
Add Hotjar tracking code to enable user survey
=> Add Hotjar tracking code

apps/nextra/pages/_document.tsx
Adds hotjar support for the Nextra site
=> [nextra] Add hotjar support

apps/docusaurus/docs/integration/wallet-adapter-concept.md, apps/docusaurus/docs/integration/wallet-adapter-for-dapp.md, apps/docusaurus/docs/integration/wallet-adapter-for-wallets.md
Following latest changes in the wallet adapter tool, updating the docs
=> Update wallet adapter docs with latest version changes

apps/nextra/components/card/Card.tsx, apps/nextra/pages/en/_meta.ts, apps/nextra/pages/en/docs/components/_meta.ts, apps/nextra/pages/en/docs/components/card.mdx, apps/nextra/pages/en/docs/components/markdown.mdx, apps/nextra/pages/en/docs/components/themed-image.mdx, apps/nextra/pages/en/docs/index.mdx, apps/nextra/pages/en/docs/setup/_meta.ts, apps/nextra/pages/en/docs/setup/migrating-from-docusaurus.mdx, apps/nextra/pages/en/network/nodes.mdx
Adding migration docs for folks helping out with docusaurus -> Nextra migration. 
=> [nextra] Docusaurus -> Nextra migration docs

apps/docusaurus/docusaurus.config.ts
add aptos learn link to the dev site
=> [aptos.dev] add Aptos Learn link to the dev site

apps/nextra/pages/en/network/nodes/validator-node/node-requirements.mdx
Add Azure instance to node requirements
=> [nextra] Add Azure instance to node requirements

apps/nextra/pages/en/network/blockchain/_meta.ts, apps/nextra/pages/en/network/blockchain/aptos-white-paper.mdx, apps/nextra/pages/en/network/blockchain/learn-about-aptos.mdx
Migrating and refactoring the Aptos White Paper page
=> [nextra] Aptos White Paper

apps/docusaurus/docs/concepts/base-gas.md, apps/docusaurus/docs/concepts/gas-txn-fee.md, apps/nextra/pages/en/build/indexer/_meta.tsx
update to reflect changes from AIP-65
=> update gas docs to reflect the latest storage fee refund scheme

apps/nextra/pages/en/build/indexer/_meta.tsx, apps/nextra/pages/en/network/nodes/full-node/pfn-requirements.mdx
Same as title. Also small linting fix for `_meta.tsx`
=> [nextra] Fix pfn requirements missing title

apps/nextra/components/graphql/NonDynamicGraphQL.tsx, apps/nextra/components/landing/components/Button.tsx, apps/nextra/components/landing/components/Icons.tsx, apps/nextra/components/landing/index.tsx, apps/nextra/components/select/Select.tsx, apps/nextra/components/tabs/Tabs.tsx, apps/nextra/components/video.tsx, apps/nextra/docs.config.js, apps/nextra/oklchColorsPlugin.cjs, apps/nextra/package.json, apps/nextra/postcss.config.cjs, apps/nextra/styles.css, apps/nextra/tailwind.config.cjs, apps/nextra/tsconfig.json, apps/nextra/utils/cn.ts, pnpm-lock.yaml
This PR adds the first section of the new landing page — the title section. Along the way, I also built a button component.
While working on this, I noticed that `@types/react` and `@types/react-dom` were missing. When I added them, it surfaced some type errors that I fixed in this PR
https://github.com/aptos-labs/developer-docs/assets/25761639/21b31aad-47b9-4a6a-845e-94a827b8b64f
=> Add title section to landing page

apps/docusaurus/docs/indexer/api/example-queries.md
=> Fix: There are spelling errors in the example

apps/nextra/pages/en/network/nodes.mdx, apps/nextra/pages/en/network/nodes/aptos-api-spec.mdx, apps/nextra/pages/en/network/nodes/local-testnet.mdx
Fix some broken links and improper formatting caused by newline on local-testnet.mdx
=> Fix local testnet

README.md, apps/nextra/.env.example, apps/nextra/README.md, package.json, prebuild.js
=> [dev-docs] Add prebuild to check for .env vars

apps/nextra/docs.config.js
=> [nextra] Add default origin in case .env doesn't exist

apps/nextra/pages/en/build/apis/aptos-labs-developer-portal.mdx, apps/nextra/pages/en/build/move/book/packages.mdx, apps/nextra/pages/en/build/move/move-on-aptos/move-security-guidelines.mdx
=> [nextra] Move + APIs content nits

apps/nextra/pages/en/build/move/move-on-aptos/object-code-deployment.mdx
Walkthrough on deploying code to objects, as part of [AIP-54](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-54.md)
=> Object code deployment walkthrough

apps/nextra/pages/en/_meta.ts, apps/nextra/pages/en/index.mdx
This changes the title to something more fitting, along with some of the menu bar items to not confuse people into thinking the `help` is for help outside of the docs, and the `developer platforms` to `external resources` to be more generic.
=> [menu bar] Update title to be more straightforward and menu items as well

apps/nextra/pages/en/network/glossary.mdx, apps/nextra/pages/en/network/glossary/index.mdx
=> [nextra] Migrate glossary

apps/nextra/pages/en/build/move.mdx, apps/nextra/pages/en/build/move/_meta.tsx, apps/nextra/pages/en/build/move/book/functions.mdx, apps/nextra/pages/en/build/move/compiler_v2.mdx, apps/nextra/pages/en/build/move/tools/compiler_v2.mdx
- Adds a new page `./move/tools/compiler_v2.mdx`
- Extends the existing function page in the Move book by documentation about receiver style calls
[None of the below commands work, various tools seem to be missing, spellcheck is unknown to pnpm]
=> [compiler-v2] Documentation for compiler beta

apps/nextra/pages/en/build/move.mdx, apps/nextra/pages/en/build/move/compiler_v2.mdx
Fixes some broken links in the new docs
=> [compiler-v2] Fixing links in docs

apps/docusaurus/docs/move/book/functions.md, apps/docusaurus/docs/move/compiler_v2.md, apps/docusaurus/docs/move/move-on-aptos.md, apps/nextra/pages/en/build/move/book/functions.mdx
Adding v2 docs also to old docsite
=> [compiler-v2] Adding docs to old docsite

apps/nextra/pages/en/build/advanced-guides/keyless-accounts.mdx
Upgrading to 1.13.3-zeta.0, we get serialization utilities for Keyless accounts. Adding to Nextra
=> [keyless] Add keyless serialization to nextra

apps/nextra/package.json, pnpm-lock.yaml
=> [deps] Upgrade next

apps/nextra/components/card/Card.tsx, apps/nextra/components/landing/sections/TitleSection.tsx, apps/nextra/docs.config.js, apps/nextra/pages/en/build/sdks.mdx, apps/nextra/pages/en/developer-platforms/_meta.ts, apps/nextra/pages/en/developer-platforms/contribute/components/card.mdx, apps/nextra/public/gas-profiling/sample-report-2/index.html
=> Pretty sdk

apps/nextra/pages/en/_meta.ts, apps/nextra/pages/en/build/_meta.tsx, apps/nextra/pages/en/build/move.mdx, apps/nextra/pages/en/build/move/_meta.tsx, apps/nextra/pages/en/build/move/examples/first-move-module.mdx, apps/nextra/pages/en/build/sdks/ts-sdk.mdx
Make Move landing page prettier, fix navigation title
=> Move revision

apps/docusaurus/docs/guides/system-integrators-guide.md, apps/docusaurus/docs/standards/fungible-asset.md, apps/nextra/pages/en/build/advanced-guides/system-integrators-guide.mdx, apps/nextra/pages/en/build/standards/fungible-asset.mdx
=> [fa] add concurrent fungible balance

apps/docusaurus/docs/guides/keyless-accounts.md
=> Update documentation to include testnet support for keyless

apps/nextra/docs.config.js, apps/nextra/pages/en/developer-platforms/contribute/setup/docs-config.mdx
=> [nextra] New Google Analytics Property

apps/nextra/components/card/Card.tsx, apps/nextra/pages/en/build/apis/fullnode-rest-api.mdx, apps/nextra/pages/en/build/indexer.mdx, apps/nextra/pages/en/build/indexer/api/labs-hosted.mdx, apps/nextra/pages/en/build/smart-contracts.mdx, apps/nextra/pages/en/developer-platforms/contribute.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/card.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/graphql-editor.mdx, apps/nextra/pages/en/network/nodes.mdx
Adds an arrow by default for Card component, configurable via the `linkType` prop
=> Fix arrow title

apps/nextra/pages/en/build/smart-contracts.mdx
Same as above + add move reference source link
=> [nextra] Add Aptos Move By Example

apps/nextra/components/remote-codeblock/RemoteCodeblock.tsx
=> [nextra] Fix RemoteCodeblock header on mobile

apps/docusaurus/docs/sdks/cpp-sdk/index.md, apps/docusaurus/src/components/sidebars.ts, apps/nextra/components/card/Card.tsx, apps/nextra/pages/en/build/sdks/_meta.tsx, apps/nextra/pages/en/build/sdks/cpp-sdk.mdx
This is a minimal page for the C++ SDK as a lot of the instructions are on the Var Meta repository
=> [sdks] Add C++ SDK

apps/docusaurus/docs/integration/wallet-adapter-for-dapp.md, apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx
=> Update adapter docs with Petra as AIP-62 compatible wallet

apps/nextra/theme.config.tsx
=> [nextra] Banner for Aptos Docs Preview with Feedback form

apps/docusaurus/docusaurus.config.ts
=> [docusaurus] Announcement bar for preview.aptos.dev

apps/nextra/pages/api/og.png.tsx
=> [nextra] Small nit on center alignment / font size on SEO card

apps/nextra/pages/en/_meta.ts
=> [nextra] Remove Advanced Guides from Dropdown

apps/docusaurus/docs/guides/randomness.md
Copy randomness guide from nextra to docusaurus.
=> randomness in docusaurus

turbo.json
=> [nextra] build:prod command added to vercel

apps/docusaurus/docs/guides/randomness.md, apps/nextra/pages/en/build/advanced-guides/randomness.mdx
Fixing some technical details.
=> randomness doc minor fix

apps/docusaurus/docs/tutorials/first-move-module.md, apps/docusaurus/static/move-examples/large_packages/large_package_example/sources/six.move, apps/nextra/pages/en/build/smart-contracts/learn-move/first-move-module.mdx
=> chore: fix some comments

apps/nextra/components/landing/sections/TitleSection.tsx, apps/nextra/pages/en/_meta.ts
=> [nextra] Remove learn CTA

apps/nextra/pages/en/build/sdks.mdx
=> [nextra] Add C++ SDK

apps/docusaurus/docs/tools/aptos-cli/use-cli/running-a-local-network.md, apps/nextra/pages/en/network/nodes/localnet/local-development-network.mdx
Explaining how to run a localnet using a container if you want. Useful for CI.
Internal context: https://aptos-org.slack.com/archives/C03N83P7QUC/p1713830713368619.
=> Explain how to run localnet in a container

apps/docusaurus/docs/tools/aptos-cli/use-cli/running-a-local-network.md, apps/docusaurus/static/sdks/typescript/examples/typescript/multisig_transaction.ts, apps/nextra/README.md, apps/nextra/pages/en/build/advanced-guides/randomness.mdx, apps/nextra/pages/en/build/cli/install-cli/install-cli-linux.mdx, apps/nextra/pages/en/build/cli/install-cli/install-cli-specific-version.mdx, apps/nextra/pages/en/build/cli/managing-a-network-node.mdx, apps/nextra/pages/en/build/indexer/_meta.tsx, apps/nextra/pages/en/build/sdks/go-sdk.mdx, apps/nextra/pages/en/build/sdks/python-sdk.mdx, apps/nextra/pages/en/build/sdks/rust-sdk.mdx, apps/nextra/pages/en/build/sdks/ts-sdk.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk.mdx, apps/nextra/pages/en/build/smart-contracts/learn-move/first-move-module.mdx, apps/nextra/pages/en/build/tutorials.mdx, apps/nextra/pages/en/build/tutorials/build-e2e-dapp.mdx, apps/nextra/pages/en/build/tutorials/build-e2e-dapp/1-create-smart-contract.mdx, apps/nextra/pages/en/build/tutorials/build-e2e-dapp/2-set-up-react-app.mdx, apps/nextra/pages/en/build/tutorials/build-e2e-dapp/3-add-wallet-support.mdx, apps/nextra/pages/en/build/tutorials/build-e2e-dapp/4-fetch-data-from-chain.mdx, apps/nextra/pages/en/build/tutorials/build-e2e-dapp/5-submit-data-to-chain.mdx, apps/nextra/pages/en/build/tutorials/build-e2e-dapp/6-handle-tasks.mdx, apps/nextra/pages/en/build/tutorials/first-coin.mdx, apps/nextra/pages/en/build/tutorials/first-fungible-asset.mdx, apps/nextra/pages/en/build/tutorials/first-move-module.mdx, apps/nextra/pages/en/build/tutorials/first-multisig.mdx, apps/nextra/pages/en/build/tutorials/first-transaction.mdx, apps/nextra/pages/en/build/tutorials/your-first-nft.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/analytics.mdx, apps/nextra/pages/en/network/nodes/localnet/local-development-network.mdx
This fixes a lot of broken links, and some tutorial content
=> Cleanup tutorials and sdks

apps/nextra/pages/en/build/smart-contracts/learn-move/advanced-guides/object-code-deployment.mdx
=> fix item index

apps/nextra/pages/en/build/smart-contracts/learn-move/advanced-guides/resource-accounts.mdx
Add note that Object Code Deployment is the recommended method to deploy and upgrade smart contracts.
=> Refer to object code deployment as recommended method vs resource accounts

.github/PULL_REQUEST_TEMPLATE.md
=> [pull-request] Make sure checkboxes have spaces in them

apps/docusaurus/docs/guides/randomness.md, apps/docusaurus/docs/integration/wallet-adapter-for-wallets.md, apps/docusaurus/docs/sdks/index.md, apps/nextra/pages/en/build/advanced-guides/randomness.mdx, apps/nextra/pages/en/build/advanced-guides/sponsored-transactions.mdx, apps/nextra/pages/en/build/cli/setup-cli/install-move-prover.mdx, apps/nextra/pages/en/build/sdks/go-sdk.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/wallets.mdx, apps/nextra/pages/en/build/smart-contracts/aptos-standards/aptos-object.mdx, apps/nextra/pages/en/network/blockchain/base-gas.mdx, apps/nextra/pages/en/network/blockchain/gas-txn-fee.mdx, apps/nextra/pages/en/network/nodes/validator-node/connect-nodes/delegation-pool-operations.mdx, apps/nextra/pages/en/network/nodes/validator-node/connect-nodes/staking-pool-operations.mdx, apps/nextra/pages/en/network/nodes/validator-node/connect-nodes/staking-pool-voter.mdx
This applies all Docusaurus fixes from external contributors since April 1st.
Additionally, formats a file that was incorrectly formatted, and fixes some spelling consistency
=> Add fixes from others

apps/nextra/pages/en/network/blockchain/_meta.ts
=> [nextra] Fix blockchain deep dive

apps/nextra/pages/en/network/blockchain/blocks.mdx
=> Fix a sentence in blocks.mdx

apps/docusaurus/docs/move/compiler_v2.md, apps/nextra/pages/en/build/smart-contracts/compiler_v2.mdx
Updates both pages old and new docset with info about bug bounty
NOTE: need to update link to bounty page before landing
=> [compiler-v2] Update beta page with bug bounty

apps/nextra/components/api-reference/ApiReference.tsx, apps/nextra/components/api-reference/DynamicApiReference.tsx, apps/nextra/components/api-reference/index.ts, apps/nextra/components/api-reference/utils.ts, apps/nextra/components/index.tsx, apps/nextra/package.json, apps/nextra/pages/en/build/apis.mdx, apps/nextra/pages/en/build/apis/_meta.tsx, apps/nextra/pages/en/build/apis/fullnode-rest-api-reference.mdx, apps/nextra/styles.css, pnpm-lock.yaml
Created a custom Fullnode API page with Scalar. Includes custom network selector.
Refactored API page as well.
=> Refactor apis

apps/nextra/components/landing/sections/DevelopersSection.tsx, apps/nextra/docs.config.js
=> [nextra] Learn added to landing page developer section

apps/nextra/pages/en/build/advanced-guides/system-integrators-guide.mdx
=> [nextra] Fix Accounts on Aptos markdown

apps/nextra/pages/en/network/nodes/_meta.tsx, apps/nextra/pages/en/network/nodes/aptos-api-spec.mdx
=> [nextra] Fix aptos api spec and networks

apps/nextra/pages/en/build/cli/running-a-local-network.mdx, apps/nextra/pages/en/network/nodes/localnet/local-development-network.mdx
=> [nextra[ Fix Faucet link on pages

apps/nextra/pages/en/build/smart-contracts/learn-move/book/abilities.mdx
=> [nextra] Remove reference to missing motivating walkthrough

apps/nextra/pages/en/build/indexer/indexer-reference.mdx
There were several incorrect links on the Indexer Table Reference page, this fixes them.
=> Fix incorrect links in indexer table reference page

apps/nextra/pages/en/build/smart-contracts/learn-move/advanced-guides/object-code-deployment.mdx
=> should use headers less often

apps/nextra/pages/en/build/advanced-guides/wallets.mdx
=> [nextra] Remove forum hyperlink

apps/nextra/pages/en/build/smart-contracts.mdx
=> [nextra] Remove Remix IDE

apps/nextra/pages/en/build/get-started.mdx, apps/nextra/pages/en/build/get-started/ethereum-cheatsheet.mdx, apps/nextra/pages/en/build/get-started/solana-cheatsheet.mdx, apps/nextra/pages/en/build/indexer.mdx, apps/nextra/pages/en/build/indexer/api/labs-hosted.mdx, apps/nextra/pages/en/build/indexer/indexer-reference.mdx
=> Many docs fixes

apps/nextra/pages/en/build/advanced-guides/system-integrators-guide.mdx, apps/nextra/pages/en/build/apis/_meta.tsx, apps/nextra/pages/en/build/apis/faucet-api.mdx
=> [nextra] Faucet API page

apps/nextra/pages/en/build/apis/_meta.tsx
=> [nextra] Rename API Gateway

apps/docusaurus/docs/aptos-keyless/how-keyless-works.md, apps/nextra/pages/en/build/smart-contracts/learn-move/_meta.tsx, apps/nextra/public/docs/fa-diagram.excalidraw
Follow up to add the excalidraw image. (Also pnpm fmt changed 2 things)
=> Add excalidraw

apps/nextra/pages/en/build/smart-contracts/aptos-standards/fungible-asset.mdx
Add section for dispatchable fungible asset.
=> Update fungible-asset.mdx 

apps/nextra/pages/en/_meta.ts, apps/nextra/pages/en/build/_meta.tsx, apps/nextra/pages/en/build/smart-contracts.mdx, apps/nextra/pages/en/build/smart-contracts/_meta.tsx
Committing this first and then fast-following with other changes to ensure others can contribute on this new structure
=> Move restructuring

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/smart-contracts/aptos-standards/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/aptos-standards/fungible-asset.mdx, apps/nextra/pages/en/build/tutorials/first-fungible-asset.mdx
1. Update grammar on FA section on Dispatchable FA
2. Update Your First FA tutorial to add Dispatchable FA - look at this [PR](https://github.com/aptos-labs/aptos-core/pull/13681)
=> Add Dispatch functions to Your First FA tutorial

apps/nextra/pages/en/build/sdks/ts-sdk/quickstart.mdx
=> [nextra] Change TS SDK Quickstart content

apps/nextra/pages/en/build/cli/trying-things-on-chain/looking-up-account-info.mdx, apps/nextra/pages/en/build/smart-contracts/_meta.tsx, apps/nextra/pages/en/build/tutorials/first-move-module.mdx
=> [ts-quickstart] Add missing import

apps/nextra/pages/en/build/sdks/ts-sdk/quickstart.mdx
=> [nextra] Fix issues with ts sdk compiling page

apps/nextra/pages/en/build/smart-contracts/fungible-asset.mdx, apps/nextra/pages/en/build/tutorials/first-fungible-asset.mdx, pnpm-lock.yaml
Minor fixes in formatting for FA docs. Previewed and looks fine now. 
=> FA docs fixes

apps/nextra/pages/en/build/smart-contracts/table.mdx
=> [nextra] Move table

apps/nextra/pages/en/build/smart-contracts/smart-table.mdx
=> [nextra] Smart Table

apps/nextra/pages/en/build/smart-contracts/smart-vector.mdx
=> [nextra] Smart Vector

apps/nextra/pages/en/build/tutorials/first-fungible-asset.mdx
=> fix broken link

apps/docusaurus/docs/create-aptos-dapp/faq.md, apps/docusaurus/docs/create-aptos-dapp/templates/digital-asset.md, apps/docusaurus/docs/create-aptos-dapp/templates/fungible-asset.md
This PR adds documentation for updating the look and feel of the UI generated by the create-aptos-dapp templates.
=> Add styling documentation for create-aptos-dapp templates

apps/nextra/pages/en/build/smart-contracts/vector.mdx
=> [nextra] Move Vector

apps/nextra/pages/en/build/smart-contracts/_meta.tsx
=> [nextra] Move Structs

apps/nextra/pages/en/build/sdks/ts-sdk/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/book/_meta.tsx
=> [book] Add separators that match the summary

apps/nextra/pages/en/build/smart-contracts/why-move.mdx
=> [nextra] Why move section

apps/nextra/pages/en/build/smart-contracts/why-move.mdx
This adds some more detail / cleanups to some grammar
=> [move] Update why move

apps/nextra/pages/en/build/smart-contracts/_meta.tsx
Adds redirects for already existing pages.  Will write content afterwards
=> Finish some sections

CODEOWNERS
=> [codeowners] update around new format

apps/nextra/pages/en/build/smart-contracts/why-move.mdx
=> [move] Update why-move again

apps/docusaurus/docs/nodes/full-node/network-identity-fullnode.md, apps/nextra/pages/en/network/nodes/full-node/modify/network-identity-fullnode.mdx
Document the ephemeral identity file location and explain that the ephemeral identity file is used between restarts
=> document ephemeral identity file

apps/nextra/pages/en/build/smart-contracts/compiling.mdx
=> [nextra] Move Compile Page

apps/docusaurus/docs/create-aptos-dapp/templates/digital-asset.md, apps/docusaurus/docs/create-aptos-dapp/templates/fungible-asset.md, apps/nextra/pages/en/build/create-aptos-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/faq.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/digital-asset.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/fungible-asset.mdx
=> Update CAD docs

apps/nextra/components/landing/sections/BlockchainSection.tsx, apps/nextra/components/landing/sections/FooterSection.tsx, apps/nextra/components/landing/sections/MoveSection.tsx, apps/nextra/pages/en/build/smart-contracts.mdx, apps/nextra/pages/en/network/blockchain.mdx, apps/nextra/pages/en/network/blockchain/aptos-white-paper.mdx
=> Polish pre launch

apps/docusaurus/docs/create-aptos-dapp/templates/fungible-asset.md, apps/nextra/pages/en/build/create-aptos-dapp/templates/fungible-asset.mdx
=> fix name in cad

apps/nextra/pages/en/build/smart-contracts/book/coding-conventions.mdx
=> [book] Update comment documentation

apps/docusaurus/docs/create-aptos-dapp/templates/digital-asset.md, apps/docusaurus/docs/create-aptos-dapp/templates/fungible-asset.md, apps/nextra/pages/en/build/create-aptos-dapp/templates/digital-asset.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/fungible-asset.mdx
Update wording for migrating to mainnet for CAD
- I ran this, there were quite a bit of misspellings
- This changed files unrelated to my PR, so I ommited the changes.
=> Updates CAD instructions for migrating to mainnet

apps/docusaurus/docs/create-aptos-dapp/templates/digital-asset.md, apps/docusaurus/docs/create-aptos-dapp/templates/fungible-asset.md, apps/nextra/pages/en/build/create-aptos-dapp/templates/digital-asset.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/fungible-asset.mdx
=> add upgrade instruction in cad

apps/nextra/public/scripts/install_cli.py, apps/nextra/public/scripts/prover_setup.sh
These scripts were previously hosted on the old site
=> [scripts] Add scripts to nextra

apps/nextra/pages/en/_meta.ts
=> Add cad to nav bar

apps/nextra/theme.config.tsx
=> [banner] Remove preview from banner

apps/nextra/next.config.mjs
This fixes a bunch of dead links that come from google searches
=> [redirects] Fix top redirects from google searches

apps/nextra/components/landing/sections/BlockchainSection.tsx, apps/nextra/pages/en/_meta.ts, apps/nextra/pages/en/build/_meta.tsx, apps/nextra/styles.css
=> Agg more fixes

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/smart-contracts/_meta.tsx
=> [nextra] References redirect

apps/nextra/next.config.mjs
Tested the redirect, confirmed it works
=> [nextra] Fix redirect for move book summary

apps/nextra/next.config.mjs
Fixes 2 redirects, one of which is used from Google.
=> [move-reference] Fix redirects for move reference

apps/nextra/pages/en/build/apis/fullnode-rest-api.mdx, apps/nextra/pages/en/build/smart-contracts/prover/prover-guide.mdx, apps/nextra/pages/en/network/glossary.mdx
=> [cli] Fix broken use-cli links

apps/nextra/pages/en/build/smart-contracts/scripts/script-tutorial.mdx
=> [Fix][en] Fix script run error

apps/nextra/components/index.tsx, apps/nextra/components/media/index.tsx, apps/nextra/pages/en/build/guides/aptos-keyless/how-keyless-works.mdx
These videos are pretty useful, and it adds more personality to the docs than just words.
=> [video] Add videos for Keyless and Randomness with Alin

apps/docusaurus/docs/sdks/ts-sdk/type-safe-contract.md, apps/nextra/pages/en/build/sdks/ts-sdk/type-safe-contract.mdx
=> nit fix surf

apps/nextra/pages/en/build/guides/aptos-keyless/oidc-support.mdx
=> Update docs to reflect Apple mainnet support for keyless

apps/nextra/pages/en/build/create-aptos-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/_meta.tsx, apps/nextra/pages/en/build/create-aptos-dapp/templates/boilerplate.mdx
=> [create-aptos-dapp] Add boilerplate template documentation

apps/nextra/pages/en/build/create-aptos-dapp/templates/digital-asset.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/fungible-asset.mdx
=> Add a Quick Start section to CAD templates

apps/nextra/components/error/Error.tsx, apps/nextra/components/error/index.tsx, apps/nextra/components/index.tsx, apps/nextra/pages/404.tsx
=> [nextra] Create custom error page for 404

apps/nextra/pages/en/build/smart-contracts/prover/supporting-resources.mdx
Add a paper reference to the resource page for the Move prover.
=> Add a paper reference to supporting-resources.mdx

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/create-aptos-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/_meta.tsx, apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx
One concern is the URL changes - any workaround?
=> [create-aptos-dapp] Fix template content and rename templates

apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx
=> Fix nft minting dapp template content

apps/nextra/pages/en/build/create-aptos-dapp/templates/_meta.tsx, apps/nextra/pages/en/build/sdks/wallet-adapter.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/_meta.tsx, apps/nextra/pages/en/build/sdks/wallet-adapter/browser-extension-wallets.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/wallets.mdx
This updates the guides for building wallet adapter plugins, as well as the main navigation page. It does not include the `Wallet Standard` page.
=> Update the Wallet Adapter section

apps/nextra/pages/en/build/create-aptos-dapp.mdx
=> Update create-aptos-dapp command

apps/nextra/pages/en/developer-platforms/contribute.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/callout.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/card.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/codeblock.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/filetree.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/graphql-editor.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/image.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/latex.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/link.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/markdown.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/mermaid.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/npm2yarn.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/organize-files.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/remote-codeblock.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/ssg.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/steps.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/table.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/tabs.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/themed-image.mdx, apps/nextra/pages/en/developer-platforms/contribute/examples/pairings.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/SEO.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/analytics.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/deployment.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/docs-config.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/maintenance.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/migrating-from-docusaurus.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/organize-files-advanced.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/organize-files.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/troubleshooting.mdx
Remove indexing for contribution section
=> [nextra] Turn off searchability in contribute section

packages/aptos-nextra-components/.eslintignore, packages/aptos-nextra-components/.gitignore, packages/aptos-nextra-components/package.json, packages/aptos-nextra-components/src/card/Card.tsx, packages/aptos-nextra-components/src/card/index.tsx, packages/aptos-nextra-components/src/index.ts, packages/aptos-nextra-components/src/test/index.tsx, packages/aptos-nextra-components/src/themed-image/ThemedImage.tsx, packages/aptos-nextra-components/src/themed-image/index.tsx, packages/aptos-nextra-components/src/utils/cn.ts, packages/aptos-nextra-components/src/utils/index.ts, packages/aptos-nextra-components/tsconfig.json, packages/aptos-nextra-components/tsup.config.ts, pnpm-lock.yaml
Creating a shared component library for components built for Nextra using `tsup` to be shared with other products that aim to use Nextra for docs. 
Publishing to npm as `@aptos-labs/nextra-components`
=> Create aptos nextra components

apps/nextra/pages/en/network/blockchain/aptos-white-paper.mdx
=> [nextra] Add spanish whitepaper

apps/nextra/pages/en/developer-platforms/contribute/setup/_meta.ts, apps/nextra/pages/en/developer-platforms/contribute/setup/mdx.mdx
Adding docs on tips for writing markdown
=> [nextra] Update the contribution section

apps/nextra/pages/en/build/create-aptos-dapp/templates/boilerplate.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx
Following https://github.com/aptos-labs/create-aptos-dapp/pull/172 , updating CAD docs to include the new deploy command
=> Update deploy to a live server section for the CAD templates

apps/nextra/pages/en/build/create-aptos-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/_meta.tsx, apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-staking-dapp.mdx
1. Fixes for the NFT minting dapp template
2. Arrange the Token minting dapp template docs to have the same format as the nft minting one
3. Add Token staking dapp template docs
=> Add Staking template docs

apps/nextra/pages/en/build/sdks/ts-sdk/fetch-data-via-sdk.mdx
- [/] Have you ran `pnpm spellcheck`?
- [/] Have you ran `pnpm fmt`?
- [/] Have you ran `pnpm lint`?
=> Fix sample code typo to get account modules

apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-staking-dapp.mdx
=> Fix CAD templates wrong content

apps/nextra/pages/en/build/create-aptos-dapp/templates/boilerplate.mdx
=> Update CAD boilerplate template to include instruction on deploying contract

.github/ISSUE_TEMPLATE/content_issue.yml
=> [issues] Add content issue template

apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-staking-dapp.mdx
https://github.com/aptos-labs/developer-docs/pull/543 landed before addressing those issues
=> Address content feedback from previous PR

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/content_issue.yml, .github/ISSUE_TEMPLATE/documentation_bug_report.md, .github/workflows/issue-label.yml
=> Amend issues and workflow

.github/workflows/ci.yml, apps/nextra/utils/generated/localeMap.ts, package.json, pnpm-lock.yaml, turbo.json
=> [ci] linting workflow

apps/nextra/pages/en/build/sdks/ts-sdk/fetch-data-via-sdk.mdx
=> Fix bug with aptos.queryIndexer example

apps/nextra/pages/en/build/create-aptos-dapp.mdx
Update Prerequisites section to CAD readme
=> Update Prerequisites section to CAD readme

apps/nextra/pages/en/build/sdks/_meta.tsx
=> Update _meta.tsx to fix emtpy swfit sdk page

apps/nextra/pages/en/build/get-started/ethereum-cheatsheet.mdx, apps/nextra/pages/en/build/get-started/solana-cheatsheet.mdx
=> [nextra] Update the aptos learn links

apps/nextra/pages/en/build/cli.mdx
=> [doc] add advanced in setup the Move Prover

apps/nextra/pages/en/build/smart-contracts/deployment.mdx
Use latest shorter commands for object code deployment
=> Use shorter commands for object code deployment

apps/nextra/pages/en/network/nodes/validator-node/deploy-nodes.mdx
This PR fixes 3 incorrect links for the validator and VFN deployment page.
=> [Nodes] Fix incorrect links for validator and VFN setup.

apps/nextra/docs.config.js
=> [issues] Add issues template to feedback link

apps/nextra/pages/en/build/smart-contracts/compiling.mdx
Named addresses now mentioned in compilation
Resolves https://github.com/aptos-labs/developer-docs/issues/561
=> Update compilation to mention named addresses

apps/nextra/pages/en/build/smart-contracts/smart-table.mdx, apps/nextra/pages/en/build/smart-contracts/smart-vector.mdx, apps/nextra/pages/en/build/smart-contracts/table.mdx, apps/nextra/pages/en/build/smart-contracts/vector.mdx
I've run all the examples through the compiler.  The table examples won't fully compile, because they must be stored at the end if not using `TableWithLength`
=> Fix smart contract docs

apps/nextra/pages/en/build/guides/aptos-keyless.mdx, apps/nextra/pages/en/build/guides/aptos-keyless/simple-example.mdx
Removing for now due to recurring `out of credits` issue. Can add back at any time once we have a better solution for this.
=> [nextra] Remove keyless iframe

apps/nextra/pages/en/build/create-aptos-dapp/templates/boilerplate.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-staking-dapp.mdx
Update CAD docs following  `npm run move:init` command deprecation
=> Update CAD template instructions

apps/nextra/pages/en/build/sdks/ts-sdk/account.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/migration-guide.mdx
=> fix account scheme mistake

apps/nextra/pages/en/build/sdks/ts-sdk/type-safe-contract.mdx
=> add missing import for surf

apps/nextra/pages/en/network/glossary.mdx
=> Add BlockSTM and Quorum Store to glossary

apps/nextra/pages/zh/_meta.ts, apps/nextra/pages/zh/build/_meta.tsx, apps/nextra/pages/zh/build/apis.mdx, apps/nextra/pages/zh/build/apis/_meta.tsx, apps/nextra/pages/zh/build/apis/aptos-labs-developer-portal.mdx, apps/nextra/pages/zh/build/apis/data-providers.mdx, apps/nextra/pages/zh/build/apis/faucet-api.mdx, apps/nextra/pages/zh/build/apis/fullnode-rest-api-reference.mdx, apps/nextra/pages/zh/build/apis/fullnode-rest-api.mdx, apps/nextra/pages/zh/build/get-started.mdx
=> Add Chinese translations, including the API and the Getting Started section.

apps/nextra/components/landing/sections/BlockchainSection.tsx, apps/nextra/pages/en/network/blockchain/_meta.ts, apps/nextra/pages/en/network/blockchain/execution.mdx
Add blockchain execution page on docs
=> [nextra] Blockchain execution

apps/nextra/pages/zh/build/apis/data-providers.mdx, apps/nextra/pages/zh/build/get-started.mdx
=> [zh] Fix chinese docs links

CODEOWNERS
=> [docs] Update codeowners

apps/nextra/pages/en/build/smart-contracts/book/enums.mdx
=> [example code] Fix wrong enum code

apps/nextra/pages/en/build/smart-contracts/fungible-asset.mdx
=> [ example code ]Modify some example code make it conform to grammatical standards.

apps/nextra/pages/en/build/indexer/fungible-asset-balances.mdx, apps/nextra/pages/en/build/indexer/token-metadata.mdx
Refresh the indexer developer docs.  
` apps/nextra/utils/generated/localeMap.ts` is updated by fmt, not included in this PR. 
=> Update the indexer docs for token data v2.

apps/nextra/pages/en/build/create-aptos-dapp/templates/clicker-game-tg-mini-app.mdx
=> [CAD] Remove seamless signing from cad tg template

apps/nextra/pages/en/build/indexer/token-metadata.mdx
tested on preview and looks good. beautiful 😎 
=> Fix the wrong query.

apps/nextra/pages/en/build/guides/system-integrators-guide.mdx, apps/nextra/pages/en/build/sdks.mdx, apps/nextra/pages/en/build/sdks/_meta.tsx, apps/nextra/pages/en/build/sdks/dotnet-sdk.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/_meta.tsx, apps/nextra/pages/en/build/sdks/dotnet-sdk/accounts/_meta.tsx, apps/nextra/pages/en/build/sdks/dotnet-sdk/accounts/ed25519.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/accounts/keyless.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/accounts/multikey.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/dotnet-examples.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/getting-started.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/godot-integration.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/transactions/_meta.tsx, apps/nextra/pages/en/build/sdks/dotnet-sdk/transactions/basic-transactions.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/transactions/sponsored-transactions.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/unity-integration.mdx, apps/nextra/pages/en/build/sdks/unity-sdk.mdx
Added the .NET SDK to the docs with guides on transactions, accounts, and integrating into platforms such as Unity or Godot.
=> [dotnet] Add .NET SDK docs

apps/nextra/pages/en/build/create-aptos-dapp/templates/boilerplate.mdx, apps/nextra/pages/en/network/glossary.mdx
=> Update API link and spelling

apps/nextra/pages/en/network/nodes/localnet/run-a-localnet.mdx, apps/nextra/pages/zh/network/nodes/localnet/run-a-localnet.mdx
=> [links] Fix a couple links

apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx, apps/nextra/pages/en/build/smart-contracts/aptos-token.mdx, apps/nextra/utils/generated/localeMap.ts
This PR updates the mentions of Irys to use our latest SDK and messaging.
- [ X] Have you ran `pnpm spellcheck`?
- [ X] Have you ran `pnpm fmt`?
- [ X] Have you ran `pnpm lint`?
=> Updated Irys to use latest tooling / messaging

apps/nextra/pages/en/build/guides/aptos-keyless/oidc-support.mdx
=> Update oidc docs

apps/nextra/pages/en/build/smart-contracts/compiling.mdx, apps/nextra/pages/en/build/smart-contracts/create-package.mdx, apps/nextra/pages/en/build/smart-contracts/deployment.mdx
Better descriptions of named addresses!
Resolves: https://github.com/aptos-labs/developer-docs/issues/612
=> [move] Improve documentation around named addresses

apps/nextra/pages/en/build/guides/exchanges.mdx
=> [exchange guide] Add more explicit native token docs

apps/nextra/pages/en/build/apis/faucet-api.mdx, apps/nextra/pages/en/build/guides/exchanges.mdx
=> [fix] fix #633

apps/nextra/pages/en/build/smart-contracts/randomness.mdx
=> randomness doc update 20241010

apps/nextra/pages/en/build/smart-contracts/error-codes.mdx
Add a section for user friendly error code descriptions
=> [error-codes] Add a more user friendly description to common questions

apps/nextra/pages/en/build/sdks/dotnet-sdk/_meta.tsx, apps/nextra/pages/en/build/sdks/dotnet-sdk/getting-started.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/queries/_meta.tsx, apps/nextra/pages/en/build/sdks/dotnet-sdk/queries/view.mdx
Add docs describing how to do view functions with no types, some types, and complex types
=> [dotnet] Add view functions docs

apps/nextra/pages/en/build/guides/aptos-keyless/oidc-support.mdx
=> Update OIDC table

apps/nextra/pages/en/network/nodes/validator-node/node-requirements.mdx
=> update disk requirement to 3TB SSD

apps/nextra/next.config.mjs
=> Fix cad redirect boilerplate template link

apps/nextra/pages/en/build/smart-contracts/book/package-upgrades.mdx
Minor fix about abilities modification during package upgrades.
=> Abilities can be added during upgrade

apps/nextra/pages/en/build/smart-contracts/linter.mdx
Add a link to the issue tracking various new lint check ideas.
=> Link to new lint rules tracking

apps/nextra/pages/en/network/blockchain/execution.mdx, apps/nextra/pages/en/network/blockchain/node-networks-sync.mdx
In response to a question about how long block close time takes, we've added that figure as of today to a couple relevant pages.
=> Add close time

apps/nextra/components/landing/components/CodeBlock.tsx
The previous link has expired and has been replaced with the latest address.
=> chore: fix 404 status URL

apps/nextra/pages/en/developer-platforms/contribute/components/ssg.mdx
=> [links] Fix next documentation link

packages/aptos-nextra-components/package.json
=> [nextra] Fix invalid prettier flag

apps/nextra/pages/en/build/smart-contracts/digital-asset.mdx
This PR updates the examples in the `Digital Asset (DA)` section to improve code structure and understanding.
=> Update digital asset examples

apps/nextra/pages/en/build/guides/exchanges.mdx
=> Add stablecoin addresses for USDT and others

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/_meta.tsx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/connect-steps.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/create-processor.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/steps.mdx
=> Connecting indexer SDK steps

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/run-processor.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/steps.mdx, packages/aptos-nextra-components/src/utils/mdast/mdast.test.ts
=> Running an indexer processor

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/_meta.tsx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/define-schema.mdx
=> Defining an indexer data schema

apps/nextra/public/scripts/install_cli.py
Occasionally people need to install older versions of the CLI, this lets them do that (on platforms where the script is supported).
```
$ python3 /tmp/install_cli.py
Latest CLI release: 6.0.0
Currently installed CLI: 6.0.0
The latest version (6.0.0) is already installed.
$ python3 /tmp/install_cli.py --cli-version 5.0.0
Installing CLI version: 5.0.0
Currently installed CLI: 6.0.0
The latest version (6.0.0) is already installed.
The version you are trying to install (5.0.0) is older than the currently installed version (6.0.0). Use --force to bypass.
$ python3 /tmp/install_cli.py --cli-version 5.0.0 --force
Installing CLI version: 5.0.0
Determined target to be: Ubuntu-22.04-x86_64
Welcome to the Aptos CLI installer!
This will download and install the latest version of the Aptos CLI at this …
```
=> Allow installing specific version of CLI with installation script

apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/steps.mdx
=> Docs on adding parallelism to indexer processor

apps/nextra/pages/en/build/smart-contracts/error-codes.mdx, apps/nextra/pages/en/build/smart-contracts/prover/spec-lang.mdx, apps/nextra/pages/en/build/smart-contracts/resource-accounts.mdx, apps/nextra/pages/ja/build/smart-contracts/error-codes.mdx, apps/nextra/pages/ja/build/smart-contracts/resource-accounts.mdx
This PR fixes some outdated description in the MSL doc and the link to the account module.
=> [prover] Update MSL doc

apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/steps.mdx
=> Add CommonSteps to the `steps` page

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/_meta.tsx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/steps.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/transaction-stream.mdx
=> transaction stream step

apps/nextra/pages/en/build/guides/key-rotation.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/building-transactions/script-composer.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/wallet-standards.mdx, apps/nextra/pages/en/build/smart-contracts/book/vector.mdx
=> chore: fix some typos

apps/nextra/theme.config.tsx
=> [nextra] banner remove jp

apps/nextra/pages/en/build/apis/data-providers.mdx
=> updated vendor list

apps/nextra/pages/en/build/smart-contracts/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/debugging.mdx
=> [debug] Add a debug guide

apps/nextra/pages/en/network/blockchain/execution.mdx
=> [links] Remove broken Sei forum link

apps/nextra/pages/en/build/sdks/ts-sdk/account/_meta.tsx, apps/nextra/pages/en/build/sdks/ts-sdk/account/account-abstraction.mdx
Added an initial guide for E2E flow of account abstraction with callouts for wallet adapter and Move implementations.
=> [abstraction] Initial guide for Account Abstraction

apps/nextra/pages/en/build/indexer/indexer-api/indexer-reference.mdx
=> Add indices to Indexer API Reference

apps/nextra/pages/en/build/guides/aptos-keyless/federated-keyless/other.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/building-transactions.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/fetch-data-via-sdk.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/quickstart.mdx
=> [links] Update TS SDK links

apps/nextra/pages/en/build/guides/aptos-keyless/oidc-support.mdx
=> Remove firebase from list of OIDC provider

apps/nextra/pages/en/build/smart-contracts/book/integers.mdx
Clarify the semantics of bit shift operations in the move book.
=> [move-book] Clarify bit shift semantics

apps/nextra/pages/en/build/guides/aptos-keyless/federated-keyless/_meta.tsx, apps/nextra/pages/en/build/guides/aptos-keyless/federated-keyless/simple-example.mdx, apps/nextra/pages/en/build/guides/aptos-keyless/simple-example.mdx
- Added a page for federated keyless example
- Updated example links to reflect the keyless example repo update
=> Add federated keyless example

apps/nextra/pages/en/build/smart-contracts/book/unit-testing.mdx
=> Fix grammar

apps/nextra/pages/en/network/nodes/bootstrap-fullnode/bootstrap-fullnode.mdx, apps/nextra/pages/zh/network/nodes/bootstrap-fullnode/bootstrap-fullnode.mdx
Looks like they've removed this feature, so I've removed it from the docs
=> [snapshots] Remove polkachu snapshots

apps/nextra/public/scripts/install_cli.py
=> [cli] Update CLI update script to use new version

apps/nextra/pages/en/build/smart-contracts/cryptography.mdx, apps/nextra/pages/zh/build/smart-contracts/cryptography.mdx
=> [links] Fix veiled coin link

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/_meta.tsx, apps/nextra/pages/en/build/indexer/nft-aggregator.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/_meta.tsx, apps/nextra/pages/en/build/indexer/nft-aggregator/nft-aggregator-table.mdx
=> add nft aggregator

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/nft-aggregator/_meta.tsx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces/bluemove.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces/rarible.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces/topaz.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces/tradeport.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces/wagmi.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces/wapal.mdx
Added pages for integrated nft marketplaces by nft aggregator
- [X ] Have you ran `pnpm fmt`?
- [X ] Have you ran `pnpm lint`?
=> add marketplaces page

apps/nextra/pages/en/build/smart-contracts/linter.mdx
Added docs for upcoming linter rule, nonminimal_bool
- If any existing pages were renamed or removed: N/A
=> [Linter] Added description for nonminimal bool linter rule

apps/nextra/pages/en/build/smart-contracts/book/functions.mdx
=> chore: fix typo in code demo

apps/nextra/pages/en/build/sdks/ts-sdk/account/account-abstraction.mdx
fix invalid module paths in account abstraction examples
=> fix invalid module paths in account abstraction examples

apps/nextra/pages/en/developer-platforms/contribute/setup/docs-config.mdx, apps/nextra/pages/en/network/nodes/validator-node/connect-nodes/staking-pool-operations.mdx
Description: 
This pull request addresses minor typographical errors in the documentation files. Specifically, it corrects the spelling of "relevant" and "commission" in the respective markdown files. These changes improve the clarity and professionalism of the documentation.
=> Fix Typos in Documentation

apps/nextra/components/beta-notice/IndexerBetaNotice.tsx, apps/nextra/pages/en/build/apis/data-providers.mdx, apps/nextra/pages/en/build/indexer/indexer-api/self-hosted.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/create-processor.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/define-schema.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/version-tracking.mdx
=> update to processor v2 repo

apps/nextra/public/scripts/install_cli.ps1, apps/nextra/public/scripts/install_cli.sh
Used Cursor to convert the script, along with my universal pkg installer.  Note that I need to find a more permanent place for the universal package installer.
There's additionally a `--generic-linux` flag specifically for getting past issues with Ubuntu x86_64 in Docker on Apple silicon.
Tested directly against Arch linux, Debian, Ubuntu.
Here's even an example running on Void linux:
```
[greg@void ~]$ curl -sSf https://raw.githubusercontent.com/aptos-labs/developer-docs/611d4ee03a00f23b026ba545c40751b1bc9510d3/apps/nextra/public/scripts/install_cli.sh | sh
Downloading universal installer...
Installing unzip...
...
[greg@void ~]$ .local/bin/aptos node run-localnet
Readiness endpoint: http://127.0.0.1:8070/
Transaction stream is starting, please wait...
Faucet is starting, please wait... …
```
=> [cli] Add installation script by CLI

apps/nextra/public/scripts/install_cli.ps1
=> [install_cli] fix color  install_cli.ps1

apps/nextra/pages/en/network/blockchain/txns-states.mdx
=> transaction size limits

apps/nextra/components/codeblock/Codeblock.tsx, apps/nextra/components/tabs/Tabs.tsx, apps/nextra/pages/en/developer-platforms/contribute/setup/troubleshooting.mdx
**Description:**
This PR includes the following fixes:
- Corrects spelling of "Customizable" in CodeBlock component documentation
- Fixes spelling of "propagates" in Tabs component documentation 
- Corrects "relevant" spelling in troubleshooting documentation
These changes improve code documentation accuracy without affecting functionality.
=> Fix typos in documentation and component comments

apps/nextra/pages/zh/build/cli.mdx
=> [i18n] zh build/cli.mdx

apps/nextra/pages/zh/build/cli/install-cli/install-cli-linux.mdx, apps/nextra/pages/zh/build/cli/install-cli/install-cli-mac.mdx, apps/nextra/pages/zh/build/cli/install-cli/install-cli-specific-version.mdx, apps/nextra/pages/zh/build/cli/install-cli/install-cli-windows.mdx
- `install-cli/install-cli-linux.mdx`
- `install-cli/install-cli-mac.mdx`
- `install-cli/install-cli-specific-version.mdx`
- `install-cli/install-cli-windows.mdx`
=> [ì8n] upgrade zh build/install-cli/*.mdx

apps/nextra/pages/en/build/smart-contracts/compiler_v2.mdx, apps/nextra/pages/en/build/smart-contracts/linter.mdx
Update documentation for compiler v2 (and minor fix for aptos move lint).
=> Compiler v2 doc update

apps/nextra/pages/zh/build/apis/_meta.tsx, apps/nextra/pages/zh/build/apis/aptos-labs-developer-portal.mdx, apps/nextra/pages/zh/build/apis/data-providers.mdx, apps/nextra/pages/zh/build/apis/faucet-api.mdx, apps/nextra/pages/zh/build/apis/fullnode-rest-api.mdx
1. build/apis/aptos-labs-developer-portal.mdx
2. build/apis/data-providers.mdx
3. build/apis/faucet-api.mdx
4. build/apis/fullnode-rest-api-reference.mdx
5. build/apis/fullnode-rest-api.mdx
=> [i18n] zh build/apis

apps/nextra/components/preload-search/DynamicPreloadSearch.tsx, apps/nextra/components/preload-search/PreloadSearch.tsx, apps/nextra/components/preload-search/index.ts, apps/nextra/pages/_app.tsx, apps/nextra/pages/_document.tsx, apps/nextra/public/sitemap-en.xml, apps/nextra/public/sitemap-zh.xml
Initial search load takes a bit of time but future searches do not incur the same penalty. This component triggers a search on load to alleviate the initial search time.
=> [nextra] Preload Search component

apps/nextra/pages/en/build/sdks/ts-sdk/building-transactions/script-composer.mdx
=> [ScriptComposer]Update Script Composer Doc

apps/nextra/pages/en/build/sdks/wallet-adapter/x-chain-accounts.mdx
- Add `EVM` integration guide
- Add a table with tested and supported wallets for each cross chain and on the Aptos network
=> Updates to the adapter x chain accounts page

apps/nextra/pages/en/build/sdks/wallet-adapter/x-chain-accounts.mdx
Reverts aptos-labs/developer-docs#918
=> Revert "Updates to the adapter x chain accounts page"

apps/nextra/pages/_app.tsx, apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx
=> Add docs on how to support mobile wallets with the adapter

apps/nextra/pages/zh/build/sdks/ts-sdk/_meta.tsx, apps/nextra/pages/zh/build/sdks/ts-sdk/confidential-asset.mdx
=> [i18n] Zh  Confidential Asset (CA)

apps/nextra/components/api-reference/ApiReference.tsx
=> [fix]fix fullnode api

apps/nextra/pages/en/build/apis/data-providers.mdx, apps/nextra/pages/zh/build/apis/data-providers.mdx
=> fix artemis link

apps/nextra/pages/en/network/nodes/validator-node/node-requirements.mdx
=> [node] Add statement on NTP requirement

apps/nextra/pages/en/build/smart-contracts/fungible-asset.mdx, apps/nextra/pages/zh/build/smart-contracts/fungible-asset.mdx
Fixes #963 
- ~[ ] Were redirects added to [next.config.mjs](../apps/nextra/next.config.mjs)?~
- ~[ ] Did you update any relative links that pointed to the renamed / removed pages?~
=> Fa docs dispatchable fix

apps/nextra/package.json, pnpm-lock.yaml
=> [deps] Upgrade next to 14.2.30

apps/nextra/pages/en/build/smart-contracts/book/structs-and-resources.mdx
=> [example] fix coin.balance -> coin.value

apps/nextra/pages/en/build/smart-contracts/linter.mdx
Add `simpler_bool_expression` documentation to linter page
=> Add `simpler_bool_expression` documentation to linter page

apps/nextra/pages/en/build/smart-contracts/linter.mdx
Added docs, this is a companion PR for [this one](https://github.com/aptos-labs/aptos-core/pull/16752).
=> Added docs for aborting_overflow_check lint

apps/nextra/pages/en/build/smart-contracts/fungible-asset.mdx
Adds an FAQ section to Aptos Fungible Asset (FA) Standard page using `<details>` and `<summary>` html markup for collapsible items.
=> Add FAQ to Aptos Fungible Asset (FA) Standard

package.json, pnpm-lock.yaml
=> [deps] Update brace-expansion

.github/workflows/ci.yml, package.json
Add and fix artifactregistry login. Taken from https://github.com/aptos-labs/developer-docs/pull/978
=> [gha] fix artifactregistry login

apps/nextra/pages/en/build/sdks/ts-sdk/account/account-abstraction.mdx
=> add disclaimer this is enabled on testnet and not mainnet.

README.md
=> update banner pointing to aptos-docs
