netlify.toml
Netlify deploy failed during initializing step. This is due to `netlify.toml` config needing to be updated as we should no longer need to define a base directory since we are now in the root of the repo.
=> [netlify] Remove "base" from Netlify config

docs/aptos-white-paper/index.md, docs/community/contributions/remix-ide-plugin.md, docs/community/index.md, docs/guides/explore-aptos.md, docs/index.md, docs/reference/glossary.md
- Fix all Ecosystem Projects links from https://github.com/aptos-foundation/ecosystem-projects to https://aptosfoundation.org/ecosystem/projects/all
- Add various Ecosystem Project links to wallets
- Add additional references to aptosfoundation.org
- Adds Ecosystem Project categories to index page
- Canonical tag for whitepaper as it exists at https://aptosfoundation.org/whitepaper to avoid [duplicate content penalty](https://ahrefs.com/seo/glossary/duplicate-content#:~:text=According%20to%20Google%2C%20most%20duplicate,%2C%E2%80%9D%20which%20includes%20scraped%20content.)
=> Fix Ecosystem references

docs/community/aptos-style.md, docs/community/site-updates.md, scripts/README.md, scripts/spellcheck.sh, static/move-examples/move-tutorial/README.md, static/sdks/python/README.md
Renames developer-docs-site -> developer-docs, fixes git references.
=> [refactor] Remove all references to `developer-docs-site`

src/components/MoveReference/index.tsx
Dynamic page loads screwed with the anchors, and didn't load them appropriately.  This should load things after page load
Thanks stack overflow https://stackoverflow.com/questions/36337703/reliably-jumping-to-named-anchor-on-dynamically-generated-page
Example:
https://deploy-preview-28--aptos-developer-docs.netlify.app/reference/move/?branch=mainnet&page=aptos-framework/doc/account.md#0x1_account_create_account_if_does_not_exist
=> [move-reference] Load page anchors after dynamic page load

src/css/custom.css
In this [PR](https://github.com/aptos-labs/aptos-core/pull/11003), we replaced "name" with "id" in anchors for the markdown files. In order to make the jump work for those anchors, the css file needs to be updated.
=> [move-reference-doc][trivial] make id work in anchor

docs/nodes/full-node/fullnode-source-code-or-docker.md, docs/nodes/full-node/update-fullnode-with-new-releases.md, docs/nodes/nodes-landing.md
Update the docs to consolidate some duplicate upgrade instructions for fullnodes. Also added clarification that wipes are only necessary for devnet
This was copied from:
https://github.com/aptos-labs/aptos-core/pull/11181
=> update fullnode release docs to clarify data wipe requirement

README.md, docs/reference/telemetry.md
I am submitting a few updates to the Aptos Developer Documentation, aimed at refining its accuracy and clarity. Below is a brief overview of the changes:
1. **Correction of Environment Variable in Telemetry Documentation (Commit: bd65d2e)**
- Addressed a discrepancy in the `telemetry.md` file. The documentation incorrectly listed `APTOS_DISBALE_TELEMETRY_PUSH_EVENTS` instead of the correct variable `APTOS_DISABLE_TELEMETRY_PUSH_EVENTS`, as consistently used in the `aptos-core` codebase (`service.rs` and `constants.rs`). This amendment aligns the documentation with the actual implementation in the repository.
2. **Revision of Step Numbering in README (Commit: bd12b36)**
- Updated the step numbering in the 'Build and serve the docs locally' section of the `README.md` for better clarity and …
=> Documentation Corrections and Enhancements

docs/tutorials/programmatic-upgradeable-module.md, docusaurus.config.js, package.json, pnpm-lock.yaml, src/components/ApiExplorer/index.tsx
This ensures mermaid can be used outside of the framework docs, but it doesn't work in move docs.
This at the minimum lets us create diagrams outside of those as well as fix it so that the API calls actually work (by not using the BCS content type)
=> [docs] Enable mermaid, fix interactivity in API stoplight

docs/index.md, docusaurus.config.js
- Fixes copyright year from static `© 2022` to utilize `Date().getFullYear` 
- Update Telegram URL to official Aptos TG channel
=> Dynamic footer copyright year & Telegram url fix

docs/move/book/SUMMARY.md, docusaurus.config.js
- The move book summary page was missing `for` loops. Added it.
- `pnpm fmt` on main suggested a change. Adding the change.
=> Minor change to summary to reflect addition of for loops.

package.json, pnpm-lock.yaml, src/components/MoveReference/index.tsx
When getting the raw markdown from http requests and parsing it into HTML with ReactMarkdown, it doesn't use the Docusaurus v2 default markdown engine. 
ref: #40 
results:
https://deploy-preview-96--aptos-developer-docs.netlify.app/reference/move/?branch=mainnet&page=aptos-framework/doc/storage_gas.md#function-dependencies
=> add remark mermaid to dynamic load markdown

apps/docusaurus/docusaurus.config.ts
I purposely did not make redirects for the legacy ts-sdk, as those docs should be eventually removed
=> [ts-sdk] Add redirects for the new ts-sdk

apps/docusaurus/docs/sdks/ts-sdk/testing.md, apps/docusaurus/docs/sdks/ts-sdk/tests.md, apps/docusaurus/src/components/sidebars.ts
Following a user feedback on not having docs around the TS SDK integration tests, adding a page covers the overall SDK tests and how one can build their own integration tests against a local node
=> Add ts sdk tests docs

apps/docusaurus/docs/guides/account-management/key-rotation.md, apps/docusaurus/docs/tutorials/first-coin.md
Replace deprecated URL links:
[https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/typescript/sdk/examples/typescript/rotate_key.ts](https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/typescript/sdk/examples/typescript/rotate_key.ts)
[https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/python/sdk/examples/rotate-key.py](https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/python/sdk/examples/rotate-key.py)
to
[https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/examples/typescript-esm/rotate_key.ts](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/examples/typescript-esm/rotate_key.ts)
[https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/python/sdk/examples/rotate_key.py](https://github.com/apto …
=> Fix: deprecated url in key-rotation.md

apps/docusaurus/docs/tutorials/first-fungible-asset.md, apps/docusaurus/docs/tutorials/your-first-nft.md
When executing `git clone`, it should create a folder in the current directory, so there's no need to cd into the home directory.
```
git clone https://github.com/aptos-labs/aptos-core.git 
```
```bash
cd ~/aptos-core/ecosystem/python/sdk
```
So, it should use the current directory.
```bash
cd ~/aptos-core/ecosystem/python/sdk => cd aptos-core/ecosystem/python/sdk
```
=> Fix:  Enter Correct Directory After Clone

README.md, apps/nextra/README.md, apps/nextra/next.config.mjs
🤞 Should fix Vercel issues not finding `@aptos-labs/aptos-nextra-config` module during Nextra `build`
=> [nextra] Transpile packages to avoid module not found issue

apps/docusaurus/docs/guides/keyless-accounts.md, apps/docusaurus/docs/tools/aptos-cli/install-cli/automated-install.md, apps/docusaurus/static/scripts/install_cli.py
This way people won't run into issues with the missing package, it'll just work. Generally when people are running this script they're installing for the first time anyway so there is no big problem if the check for the current version fails.
On a Linux machine:
```
python install_cli.py
```
I ran it as normal and it worked. I then made the first two blocks throw an ImportError and it worked as intended too.
=> [CLI] Handle when packaging / distutils is absent in CLI installation script

apps/docusaurus/docs/concepts/txns-states.md, apps/docusaurus/docs/guides/account-management/key-rotation.md, apps/docusaurus/docs/guides/system-integrators-guide.md, apps/docusaurus/docs/sdks/index.md, apps/docusaurus/docs/sdks/legacy-ts-sdk/index.md, apps/docusaurus/docs/sdks/python-sdk/index.md, apps/docusaurus/docs/sdks/rust-sdk/index.md, apps/docusaurus/docs/sdks/unity-sdk/index.md, apps/docusaurus/docs/standards/multisig-managed-fungible-asset.md, apps/docusaurus/docs/tutorials/first-coin.md, apps/docusaurus/docs/tutorials/first-fungible-asset.md, apps/docusaurus/docs/tutorials/first-move-module.md, apps/docusaurus/docs/tutorials/first-multisig.md, apps/docusaurus/docs/tutorials/first-transaction.md, apps/docusaurus/docs/tutorials/your-first-nft.md, apps/docusaurus/src/components/sidebars.ts, apps/docusaurus/static/move-examples/large_packages/large_package_example/sources/five.move, apps/docusaurus/static/sdks/rust/README.md
This is reformatting the docs around Rust and Python SDKs to add pages on usage of each.
=> [sdks] Move SDKs all to folders

apps/docusaurus/docs/move/book/functions.md
The entry function cannot have a return value.
=> [docs] Fix entry fun return value

apps/docusaurus/docs/sdks/ts-sdk/index.md
If the requested amount of funds at the beginning is too low, it will result in subsequent transactions by the user failing.
should: `amount: 100000000`
```
await aptos.fundAccount({ accountAddress: alice.accountAddress, amount: 1000 });
```
`coin tranfer` cannot send the coin to a recipient without a CoinStore.
We need to use `0x1::aptos_account::transfer_coins`
```
function: "0x1::coin::transfer",
typeArguments: ["0x1::aptos_coin::AptosCoin"],
functionArguments: [bobAddress, 100],
```
=> [ts-sdk] Fix parameter error in ts-sdk example 

apps/docusaurus/docs/guides/local-development-network.md
This error has popped up once or twice and there's not much we can do in the CLI about it, let's mention it in the docs.
=> Add entry to local testnet FAQ about 'too many open files' error

apps/docusaurus/docs/tutorials/your-first-nft.md
I noticed that in the "Your First NFT" documentation, under "Step 2: Run the example", there is only a mention of running pnpm install within the "example/typescript-esm" directory. However, the command to run the example, "pnpm run simple_digital_asset", executes "ts-node --esm dist/simple_digital_asset.js", which relies on the JavaScript files in the "dist" directory. This directory is only created after running "pnpm build", but the documentation does not specify the need to run "pnpm build" within the "example/typescript-esm" directory. The instructions only include a build step for the "aptos-ts-sdk".
I have added the missing build step to the documentation to ensure clarity and prevent potential confusion for users trying to run the example.
- [] Have you ran …
=> [docs] Add missing build step to "Your First NFT" documentation

apps/docusaurus/docs/tutorials/build-e2e-dapp/1-create-smart-contract.md
This pull request addresses a minor issue with the numbering of steps in the 'Add validations' section of the '1-create-smart-contract.md' tutorial.
- The second step, which was incorrectly numbered as `1.`, has been corrected to `2.` to reflect the proper sequence.
The change ensures that the tutorial's instructions are clear and logically ordered, which can prevent confusion for developers following the guide.
The corrected section now reads:
As this code now compiles, we want to have some validations and checks before creating a new task or updating the task as completed, so we can be sure our functions work as expected.
1. Add a check to the `create_task` function to make sure the signer account has a list:
...
2. Add a check to the `complete_task` function to make sure the:
- signer …
=> Fix: Correct step numbering in smart contract 'Add validations' section

apps/docusaurus/docs/tutorials/your-first-nft.md
I have submitted a pull request addressing an issue in the "Your First NFT" chapter of the documentation. It was observed that the [Aptos Typescript SDK](https://github.com/aptos-labs/aptos-ts-sdk/blob/7d257b76730e54b524fc3bc3d163d6f6a55af7ed/src/api/digitalAsset.ts#L133) no longer includes the getOwnedTokens API. This API has been updated to getOwnedDigitalAssets.
The "Your First NFT" chapter was still using the outdated API, which could lead to confusion or errors for users following the guide. To rectify this, I have updated the documentation to use the new getOwnedDigitalAssets API, ensuring the documentation remains accurate and up-to-date with the current Aptos Typescript SDK.
Please review the changes and merge the pull request if everything is in order. This update will help …
=> [docs] Update deprecated API usage in "Your First NFT" chapter

apps/nextra/.prettierignore, apps/nextra/package.json
Ignore `.next` folder (build folder)
=> [nextra] Fix prettier linting - ignore .next

apps/nextra/theme.config.tsx
Was making it difficult to see content under certain directories. Kept [defaultCollapseLevel](https://nextra.site/docs/docs-theme/theme-configuration#menu-collapse-level) at 1 though.
=> [nextra] Remove autocollapse

.eslintrc.js, pnpm-lock.yaml, pnpm-workspace.yaml, workers/code-cache/.gitignore, workers/code-cache/README.md, workers/code-cache/drizzle.config.json, workers/code-cache/drizzle/0000_faithful_daredevil.sql, workers/code-cache/drizzle/0000_short_lockheed.sql, workers/code-cache/drizzle/meta/0000_snapshot.json, workers/code-cache/drizzle/meta/_journal.json, workers/code-cache/package.json, workers/code-cache/src/github.spec.ts, workers/code-cache/src/github.ts, workers/code-cache/src/index.ts, workers/code-cache/src/schema.ts, workers/code-cache/src/utils.ts, workers/code-cache/tsconfig.json, workers/code-cache/vitest.config.js, workers/code-cache/wrangler.toml
Github Code Cache backend setup with Cloudflare workers and Cloudflare D1. 
Given a github permalink (or several github permalinks), the API requests code snippets from github API, stores it in a SQLite cache using Cloudflare D1, and then retrieves it from cache upon subsequent requests.
- Setup middleware for CORS headers and api key authentication of requests
- Notable Routes
- **POST** `/codecache` -> Fetches `github_permalinks` and adds to cache
- **POST** `/codecache/used-in-latest-docs` -> Enables a developer to know if a permalink was used in the latest docs build
Endpoint: `https://code-cache.petra-wallet.workers.dev/`
=> Code cache

apps/nextra/middleware.ts, apps/nextra/package.json, pnpm-lock.yaml
This adds '/' -> '/en' and '/fr' etc. -> '/en' for now.
I wanted to change all of '/en' to just '/', but there's some hydration issue when using a rewrite.
=> [nextra] i18n - add middleware to handle unhandled languages

apps/nextra/pages/en/build/move/move-on-aptos/third-party-dependencies.mdx
A new section detailing third party dependencies in terms of:
* Sourced locations
* Limitations
* Attributes
* and Package Support
There are `details` sections that give literal examples to convey the package setup requirements, in both the `Bytecode` section and `ABI` section. Although I think an example is needed for these more complicated setups, there might be a better place to put them (assuming we want to keep examples outside of this area).
=> [nextra] Add `Third Party Dependencies` section to `Move on Aptos`.

apps/nextra/pages/en/_meta.ts
Token hub doesn't have a URI, and want to hide the docs help with a more sensible name
=> Move docs help into additional resources, and remove token hub

apps/nextra/pages/en/build/apis/_meta.tsx, apps/nextra/pages/en/build/apis/fullnode-rest-api.mdx, apps/nextra/pages/en/build/indexer.mdx
Add links to fullnode spec for API page for `mainnet`, `testnet`, `devnet`. Also fix some small things in indexer.
=> [nextra] Add API explorer links

apps/docusaurus/docs/move/move-on-aptos.md
Link to Aptos Learn as a more ideal tutorial location
=> [docusaurus] Put a tip pointing users to Aptos learn on the move page

apps/nextra/components/landing/sections/TitleSection.tsx, apps/nextra/docs.config.js
- Remove "only possible on Aptos" from Blockchain Features section as requested from Marketing. 
- Remove unnecessary External Link Icon from "Quick Start" CTA button. The purpose is to indicate that clicking the link will take the user to an external website, however this is an internal link.
=> Remove unnecessary External Link Icon & Copy Edit for Blockchain Features heading

apps/nextra/components/landing/components/Accordion.tsx, apps/nextra/components/landing/sections/BlockchainSection.tsx, apps/nextra/components/landing/sections/DevelopersSection.tsx, apps/nextra/components/landing/sections/MoveSection.tsx, apps/nextra/components/landing/sections/TestimonialsSection.tsx, apps/nextra/components/landing/sections/ToolingSection.tsx
This PR removes all the double borders from the landing page.
=> Remove double borders from landing page

apps/docusaurus/docs/move/book/functions.md, apps/nextra/pages/en/build/move/book/functions.mdx
Fixes https://github.com/aptos-labs/aptos-core/issues/12043.
- refine statement about `break` and `continue` in lambda.
- add some discussion of `inline` and reference parameters/ results.
=> Fixes to inline function docs in Aptos Move book

apps/docusaurus/docs/standards/aptos-object.md, apps/nextra/pages/en/build/standards/aptos-object.mdx
This PR addresses syntax errors in the examples provided in the Object documentation, enhancing clarity and understanding. 
Users can more easily comprehend the code logic, thereby improving the readability and usability of the documentation.
=> [aptos-object] Fix syntax errors in Object examples

apps/nextra/pages/en/build/apis/fullnode-rest-api.mdx, apps/nextra/pages/en/build/indexer.mdx, apps/nextra/pages/en/build/indexer/api/labs-hosted.mdx, apps/nextra/pages/en/build/move.mdx, apps/nextra/pages/en/developer-platforms/contribute.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/card.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/graphql-editor.mdx, apps/nextra/pages/en/network/nodes.mdx
Discussed with Jing offline, arrow icons on cards help denote links better.
=> [nextra] Add arrow icons on internal / external links

apps/docusaurus/docs/standards/fungible-asset.md, apps/nextra/pages/en/build/cli/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/learn-move/advanced-guides/scripts/running-scripts.mdx
=> Fix running move scripts with ts sdk

apps/docusaurus/docs/standards/fungible-asset.md, apps/nextra/components/landing/sections/FooterSection.tsx
This changes the careers link to the ecosystem job board, and fixes a link to the old aptos.dev site.
=> [nextra] Fix some landing links

apps/nextra/next.config.mjs
Adds redirects for all pages which have the same filename before / after the migration.  
Verified that all migrated links worked: (Mismatches listed are expected as the "title" for those pages changed, but the redirect worked properly). 
[verification.txt](https://github.com/aptos-labs/developer-docs/files/15383422/verification.txt)
Happy to share the scripts I used if they're helpful, but this seems one-time use so I didn't want to clutter the library.
In a future PR, I will go in and update the remaining links (~ (Some have to be migrated still, some were no longer needed (Ex. `in-korean.mdx`, and some were rewritten so I need to redirect them by hand to the new organization). There's about 40 links remaining (This PR fixes 150 links)
- [] Have you ran `pnpm …
=> Add redirects for most migrated pages

apps/docusaurus/docs/integration/wallet-adapter-for-dapp.md, apps/docusaurus/docs/integration/wallet-adapter-for-wallets.md, apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/wallets.mdx
=> Update wallet adapter docs on AIP-62 standard

apps/docusaurus/docs/guides/randomness.md, apps/nextra/pages/api/og.png.tsx, apps/nextra/pages/en/build/advanced-guides/_meta.tsx, apps/nextra/pages/en/build/advanced-guides/randomness.mdx
=> randomness doc inital

apps/nextra/pages/en/_meta.ts, apps/nextra/pages/en/build/smart-contracts/aptos-standards/fungible-asset.mdx, apps/nextra/pages/en/build/smart-contracts/learn-move/advanced-guides/object-code-deployment.mdx
Changes to add clarity on object code deployment section. Namely, changed all instances of `your_module_name` because it was actually referring to named addresses, not module names. 
Changes to FA section: added untransferable for primary stores since devs should be clear on the fact that just because secondary stores can be transferred, doesn't mean that primary stores can. Transfer is disabled for pfs.
=> changes to object code deployment

apps/nextra/pages/en/build/apis/_meta.tsx
Relative path redirects change based on the page you're clicking from unfortunately. Setting it to an absolute path instead
=> [nextra] fix href absolute path

README.md, apps/docusaurus/docs/create-aptos-dapp/faq.md, apps/docusaurus/docs/create-aptos-dapp/index.md, apps/docusaurus/docs/create-aptos-dapp/templates/digital-asset.md, apps/docusaurus/docs/create-aptos-dapp/templates/fungible-asset.md, apps/docusaurus/docusaurus.config.ts, apps/docusaurus/src/components/sidebars.ts
This PR adds a documentation for `create-aptos-dapp`.
Some minor content is missing and will add it later but wanted to get this out to have
1. A review on the page structure
2. English check
What is the status with the new doc site? should we copy the same content to there also? if so, once it looks good, I can copy everything to nextra
Questions:
I tried to use a nested list but couldn't find a way to display it nicely  https://github.com/aptos-labs/developer-docs/pull/438/files#diff-76263fbad0317ff827afa03f31f953912a8b4336a2c031276085a7d59e2c3ad6R53-R56
=> Add `create-aptos-dapp` doc

apps/docusaurus/docs/sdks/ts-sdk/type-safe-contract.md, apps/nextra/pages/en/build/sdks/ts-sdk/type-safe-contract.mdx
Use pure powershell script instead of node script. We will still use node script in create aptos dapp, but on doc pure powershell script is better because users don't need to install any cli.
Tested on a windows machine.
=> update windows script on how to get abi

apps/nextra/pages/en/build/create-aptos-dapp/templates/digital-asset.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/fungible-asset.mdx
- Removes unneeded code block
- Remove use of `yarn/pnpm/bun` as the tool currently only supports `npm`
=> Fix create-aptos-dapp templates

apps/nextra/components/framework-reference/index.tsx, apps/nextra/components/index.tsx, apps/nextra/pages/en/build/smart-contracts/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/move-reference.mdx
We can host the move reference on a friendlier site, and just iframe it in since the experience seems to be really rough for integrating it into Nextra.
This is an alternative to sending people away from the nextra site.
=> [move-reference] Put move reference in an iframe from the legacy site

apps/nextra/pages/en/build/smart-contracts/objects/creating-objects.mdx
The first argument passed in function 'create_named_address' is incorrect. It should be &signer.
=> Fixed create_named_address argument from caller_address to caller

apps/nextra/pages/en/build/smart-contracts/move-security-guidelines.mdx
Fix typo inside move security guidelines
=> Fix typo inside move sec. guidelines

apps/nextra/pages/en/network/nodes/bootstrap-fullnode/bootstrap-fullnode.mdx
This PR adds a small warning to the `Bootstrap from a Snapshot` page (specifically that indexer snapshotting is not supported).
=> [Nodes] Add small warning to snapshot bootstrapping

apps/nextra/next.config.mjs
Fix redirect loop for `https://aptos.dev/move/book/summary/` which is the [top result on google](https://www.google.com/search?q=aptos+move+book&oq=aptos+move+book&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDwyBggCEEUYPDIGCAMQLhhA0gEIMTQzNWowajGoAgCwAgA&sourceid=chrome&ie=UTF-8) for "aptos move book"
=> [redirects] Fix redirect loop for /move/book/summary

package.json, pnpm-lock.yaml
Fixes a dependabot alert.  Didn't see any changes in the indexer plugin, or the API plugin.
=> [deps] upgrade ws

apps/nextra/next.config.mjs
This redirect was causing an infinite loop of redirecting since urls don't care about capitalization. 
=> Fix broken redirect

apps/docusaurus/docs/create-aptos-dapp/templates/fungible-asset.md, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx
Change docs to say `fa_address` instead of `asset_id` for our token minting template in create-aptos-dapp.
Related PR: https://github.com/aptos-labs/create-aptos-dapp/pull/162#pullrequestreview-2208899812
Updated doc:
=> change asset_id -> fa_address

apps/nextra/pages/en/build/sdks/ts-sdk/account.mdx
Method `fromPrivateKeyAndAddress` is deprecated https://github.com/aptos-labs/aptos-ts-sdk/blob/main/src/account/Account.ts#L166
=> Update generate account with ts sdk docs

apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx
This PR just adds a bit more clarity around the `shadcn/ui` wallet selector and BYO wallet selector guide.
The `shadcn/ui` wallet selector isn't actually a package, but rather code you can copy into your codebase and edit yourself so I removed the word "package" from its description.
Also I mentioned that the guide linked can be useful if you want to build your wallet selector instead of using one of the wallet selectors that we provide.
=> Tweak wording around wallet selector UI package docs

apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx
Pontem is AIP-62 compatible wallet, so changing to use OKX in the docs
=> Use OKX wallet instead of Pontem for a non aip-62 compatible wallet example

apps/nextra/pages/en/build/sdks/go-sdk.mdx, apps/nextra/pages/en/build/sdks/go-sdk/_meta.tsx, apps/nextra/pages/en/build/sdks/go-sdk/account.mdx, apps/nextra/pages/en/build/sdks/go-sdk/building-transactions.mdx, apps/nextra/pages/en/build/sdks/go-sdk/building-transactions/_meta.tsx, apps/nextra/pages/en/build/sdks/go-sdk/building-transactions/batching-transactions.mdx, apps/nextra/pages/en/build/sdks/go-sdk/building-transactions/bcs-format.mdx, apps/nextra/pages/en/build/sdks/go-sdk/building-transactions/multi-agent-transactions.mdx, apps/nextra/pages/en/build/sdks/go-sdk/building-transactions/simulating-transactions.mdx, apps/nextra/pages/en/build/sdks/go-sdk/building-transactions/sponsoring-transactions.mdx, apps/nextra/pages/en/build/sdks/go-sdk/fetch-data-via-sdk.mdx, apps/nextra/pages/en/build/sdks/go-sdk/go-examples.mdx, apps/nextra/utils/generated/localeMap.ts
Adds Go SDK docs that mirror the TypeScript docs.
Some parts are commented out that should be there, but the functionality doesn't exist.
=> [go-sdk] Add docs to match the TypeScript SDK

apps/nextra/pages/en/build/smart-contracts/book/SUMMARY.mdx, apps/nextra/pages/en/build/smart-contracts/book/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/book/abort-and-assert.mdx, apps/nextra/pages/en/build/smart-contracts/book/enums.mdx, apps/nextra/pages/en/build/smart-contracts/book/functions.mdx, apps/nextra/pages/en/build/smart-contracts/book/global-storage-operators.mdx, apps/nextra/pages/en/build/smart-contracts/book/integers.mdx, apps/nextra/pages/en/build/smart-contracts/book/move-2.0.mdx, apps/nextra/pages/en/build/smart-contracts/book/structs-and-resources.mdx, apps/nextra/pages/en/build/smart-contracts/book/vector.mdx, apps/nextra/pages/en/build/smart-contracts/compiler_v2.mdx
Adds documentation derived from our internal preparation documents. Also adds an overview page for Move 2 which links to other sections in the book.
One way to view this is via the latest vercel preview deployment which can be seen in the PR activity.
[All CI tests passed]
=> [move-book] Extending Book by Move 2.0 Documentation

apps/nextra/pages/en/build/create-aptos-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/boilerplate.mdx
Based on https://github.com/aptos-labs/create-aptos-dapp/pull/199 , renaming `move` folder to `contract`.
Also, updating the docs on the Boilerplate template
=> Rename `move` folder to `contract` and update Boilerplate docs

apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx
Move collection address and fa address from `config.ts` to `.env`. 
CAD PR https://github.com/aptos-labs/create-aptos-dapp/pull/195
=> Update cad instructions

apps/nextra/pages/en/build/get-started/developer-setup.mdx, apps/nextra/utils/generated/localeMap.ts, pnpm-lock.yaml
Adds a `Create Aptos Dapp` section to the [Get Started | Developer Setup](https://aptos.dev/en/build/get-started/developer-setup) page.
=> Add Create Aptos Dapp section to get started -> developer setup

apps/nextra/pages/en/build/cli/_meta.tsx, apps/nextra/pages/en/build/cli/start-from-template.mdx, apps/nextra/pages/en/build/smart-contracts/create-package.mdx
Adds a section under`CLI` -> `Get Started` called `Start from template` that demonstrates how to set up a Move package from a template. Uses this command:
```bash
aptos move init --name hello_blockchain --template hello-blockchain
```
=> Add "Start from template" step under CLI -> Get Started

apps/nextra/pages/en/network/blockchain/accounts.mdx
=> [account] Fix Multikey authentication key docs

apps/nextra/pages/en/build/smart-contracts/book/structs-and-resources.mdx
While implementing the move lint check here https://github.com/aptos-labs/aptos-core/pull/14581, I realized that we had some incorrect documentation about dereferencing borrows in the move book.
This PR aims to rectify that.
=> [move book] Fix doc about explicit dereference and borrow

apps/nextra/pages/en/build/cli/install-cli/install-cli-windows.mdx, apps/nextra/pages/zh/build/cli/install-cli/install-cli-windows.mdx
I just tried to install the CLI on a fresh Windows installation using an admin powershell and nothing happened with the existing command, it insta fails with an error that flashes too fast to see.
This command works. I also confirmed it works with non admin powershell.
=> Fix CLI installation command

apps/nextra/pages/en/build/sdks/ts-sdk/_meta.tsx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/migration-guide.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/sdk-client-layer.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/sdk-client-layer/aptos-client.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/sdk-client-layer/indexer-client.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/sdk-core-layer.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/sdk-plugins-layer.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/sdk-tests.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/typescript-sdk-overview.mdx
Adds deprecation notice to all legacy SDK pages.  This should redirect users to the new SDK.
=> [legacy-ts-sdk] Add deprecation notice to top of all of the legacy TS SDK Docs

apps/nextra/pages/en/build/create-aptos-dapp/templates/nft-minting-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/token-minting-dapp.mdx
Updates links to Irys.xyz that were broken and pointing to an old version of their docs. This should also fix the `linkChecker` job.
The only actual change is 2 lines where I changed the link. I think Webstorm must have taken it upon itself to trim lines.
=> Updates Irys links that were failing link checker

apps/nextra/pages/en/build/smart-contracts/book/enums.mdx
In this PR, we add documentation about destroying (non-droppable) enum values.
=> [move-2] Add documentation about destroying enum values

apps/nextra/pages/en/build/smart-contracts/objects.mdx
This PR adds the key ability to MyStruct1 and MyStruct2 and passes constructor_ref by reference as generate_signer expects a 
reference to ConstructorRef
=> Add "has key" to structs and pass constructor_ref by reference

apps/nextra/pages/en/build/smart-contracts/objects.mdx, apps/nextra/pages/en/build/smart-contracts/objects/using-objects.mdx
Removes docs about object burn, as the feature will be removed.
See: https://github.com/aptos-foundation/AIPs/pull/492
=> [object] Remove object burn docs

apps/nextra/pages/en/build/create-aptos-dapp.mdx, apps/nextra/pages/en/build/create-aptos-dapp/templates/_meta.tsx, apps/nextra/pages/en/build/create-aptos-dapp/templates/custom-indexer.mdx
CAD PR https://github.com/aptos-labs/create-aptos-dapp/pull/226
=> [CAD] Add CAD custom indexer template

apps/nextra/pages/en/build/smart-contracts/objects/creating-objects.mdx
This PR addresses compiler errors and warnings by passing correct arguments into functions as per their signature and removing unused imports that were causing warnings
=> Address some compiler warnings and errors

apps/nextra/pages/en/build/apis/faucet-api.mdx
`faucetClient.fund({...})`
```error
TypeError: faucetClient.fund is not a function
```
```
(property) AptosFaucetClient.fund: FundService
readonly fund: FundService;
```
`faucetClient.fund.fund({...})`
```success
{
"txn_hashes": [
"1fb395065a4f2ccd7dcc8d330655be278111b34366873b896181de9eff6852ad"
],
"__headers": {
"content-length": "83",
"content-type": "application/json; charset=utf-8"
}
}
```
```ts
async function callFaucet(
amount: number,
address: string
): Promise<string[]> {
const faucetClient = new AptosFaucetClient({
BASE: 'https://faucet.testnet.aptoslabs.com',
})
const request: FundRequest = {
amount,
address,
}
try {
const response = await faucetClient.fund.fund({ requestBody: request })
console.log(response)
if ('txn_hashes' in response) {
return response.txn_hashes
} else { …
```
=> fix TS syntax error: to `faucetClient.fund.fund({ ... })`

apps/nextra/pages/en/build/smart-contracts/objects/using-objects.mdx
This PR adds necessary ability constraints to generic parameters and ensures that `create_primary_store_enabled_fungible_asset` is called with correct arguments
=> [smart-contracts] modify some code examples

apps/nextra/pages/en/build/smart-contracts/book/variables.mdx
Add documentation for the op equals https://github.com/aptos-labs/aptos-core/pull/14583.
=> [Move Book] Add documentation for op equal

apps/nextra/pages/en/build/create-aptos-dapp/templates/custom-indexer.mdx
=> Always instruct people to run indexer in docker

apps/nextra/pages/en/build/indexer/fungible-asset-balances.mdx
Error: Variables are invalid JSON: Expected ',' or '}' after property value in JSON at position 106 (line 4 column 1).
Variables are invalid JSON: Expected ',' or '}' after property value in JSON at position 106 (line 4 column 1).
=> fix invalid JSON

apps/nextra/pages/en/build/smart-contracts/book/SUMMARY.mdx, apps/nextra/pages/en/build/smart-contracts/book/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/book/loops.mdx, apps/nextra/pages/en/build/smart-contracts/book/move-2.mdx, apps/nextra/pages/en/build/smart-contracts/compiler_v2.mdx
Adds loop label documentation and updates the release notes.
CI will show, those do not work on my machine locally.
=> [move book] Adding docs for 2.1 language release

apps/nextra/pages/zh/build/_meta.tsx, apps/nextra/pages/zh/build/apis/_meta.tsx, apps/nextra/pages/zh/build/sdks/ts-sdk/account.mdx
Add zh doucment Typescript-sdk / account.mdx
=> [document] Add zh doucment  Typescript-sdk / account.mdx

apps/nextra/next.config.mjs
A redirect for old doc page to new one
Example: https://developer-docs-nextra-git-move-2-redirect-aptoslabs.vercel.app/en/build/smart-contracts/book/move-2.0
=> [redirect] Point move-2.0 to move-2

apps/nextra/pages/en/network/nodes/validator-node/deploy-nodes/using-aws.mdx, apps/nextra/pages/en/network/nodes/validator-node/deploy-nodes/using-azure.mdx, apps/nextra/pages/en/network/nodes/validator-node/deploy-nodes/using-gcp.mdx, apps/nextra/pages/zh/network/nodes/validator-node/deploy-nodes/using-aws.mdx, apps/nextra/pages/zh/network/nodes/validator-node/deploy-nodes/using-azure.mdx, apps/nextra/pages/zh/network/nodes/validator-node/deploy-nodes/using-gcp.mdx
The `mainnet` branch is deprecated and Terraform configs should always be obtained from the `main` branch, which is the default.
=> Fix Terraform module source reference

apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/legacy-ts-sdk/migration-guide.mdx
The warnings in the Legacy TS SDK had broken links to the new version. This fixes those 2 pages.
=> Fix broken links in Legacy TS SDK section

apps/nextra/pages/en/build/smart-contracts/book/package-upgrades.mdx
Adding a link to enum type upgrade compatibility rules from where we list package upgrade rules.
=> Add a link to enum compatibilty rules

apps/nextra/pages/en/build/cli/setup-cli/install-move-prover.mdx
This PR updates the doc on how to install dependencies for Move prover.
=> [doc][prover] add doc for installing Move prover dependencies

apps/nextra/pages/en/build/smart-contracts/_meta.tsx, apps/nextra/pages/en/build/smart-contracts/linter.mdx
Adds a new doc page about various `aptos move lint` checks.
=> Aptos Move Linter Documentation Page

apps/nextra/pages/en/build/smart-contracts/book/move-2.mdx
Add doc about underscore function params not being bound starting from Move 2.1.
=> Add non-binding underscore function parameter feature to move 2.1 release notes

apps/nextra/pages/en/build/cli/working-with-move-contracts/arguments-in-json-tutorial.mdx, apps/nextra/pages/en/build/guides/first-multisig.mdx, apps/nextra/pages/en/build/smart-contracts/book/packages.mdx, apps/nextra/pages/en/build/smart-contracts/book/unit-testing.mdx, apps/nextra/pages/en/build/smart-contracts/create-package.mdx, apps/nextra/pages/en/build/smart-contracts/scripts/compiling-scripts.mdx, apps/nextra/pages/en/build/smart-contracts/third-party-dependencies.mdx, apps/nextra/pages/zh/build/cli/working-with-move-contracts/arguments-in-json-tutorial.mdx
This migrates the developer docs to use dependencies from the newly-setup aptos-framework repo.
=> aptos-framework repo migration: developer docs [3/n]

apps/nextra/pages/en/build/smart-contracts/book/move-2.mdx
Document the well specified evaluation order starting from Move 2.
=> Document well defined eval order starting from Move 2

apps/nextra/components/buttons/Button.tsx
=> fix "mr-2" Button.tsx

apps/nextra/pages/en/build/sdks/ts-sdk/building-transactions/multi-agent-transactions.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/building-transactions/simulating-transactions.mdx, apps/nextra/pages/en/build/sdks/ts-sdk/building-transactions/sponsoring-transactions.mdx
This PR adds the documentation for the change in https://github.com/aptos-labs/aptos-ts-sdk/pull/467 (AIP-92: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-92.md).
=> Add the documentation for the transaction simulation enhancement

apps/nextra/pages/en/build/smart-contracts/book.mdx, apps/nextra/pages/en/developer-platforms/contribute/setup/migrating-from-docusaurus.mdx
1. Fixed grammar in book.mdx:
- Changed: "developers who are with some programming experience"
- To: "developers with some programming experience"
2. Fixed typo in migrating-from-docusaurus.mdx:
- Changed: "relevent `filename`"
- To: "relevant `filename`"
=> Fix typos and grammar in documentation

apps/nextra/pages/en/build/guides/oracles.mdx
Hi all, Mario from Pyth here. Would like to add Pyth oracle and how to use Pyth on Aptos for developers 
=> add Pyth to Aptos

apps/nextra/pages/en/build/smart-contracts/book/bool.mdx, apps/nextra/pages/en/build/smart-contracts/book/enums.mdx
Changes made:
1. Fixed "built-to" to "built into" in bool.mdx documentation
2. Fixed syntax error in enums.mdx - corrected closing bracket in Rectangle pattern matching
3. Changed "That following" to "The following" in enum upgrade description
4. Fixed formatting and syntax in code examples
These changes improve readability and correctness of the Move language documentation.
=> Fix grammatical and syntax errors in Move documentation

apps/nextra/pages/en/build/smart-contracts/move-security-guidelines.mdx
Insert access control check for pause/unpause functionality inside the move sec. guidelines
=> Insert access control check for pause/unpause functionality inside the move sec. guidelines

apps/nextra/components/move-reference/ModuleContainer.tsx
When opening the move reference page on a specific module (e.g. https://aptos.dev/en/build/smart-contracts/move-reference?page=move-stdlib%2Fdoc%2Fstring.md), the dropdown will always show the default value (but will correctly update when a user makes a selection).
This change ensures that the correct value is displayed at all times.
**Wrong value in dropdown**
=> [Move reference] show correct module in dropdown on page load

apps/nextra/pages/en/build/smart-contracts/objects/creating-objects.mdx
This PR modifies One-Time Transfers example (`LinearTransferRef`). Since `LinearTransferRef` does not have store ability, it is created within the function using `TransferRef` instead of storing it inside the resource.
=> [creating-objects] fix one time transfers example

apps/nextra/pages/en/network/blockchain/resources.mdx, apps/nextra/pages/en/network/nodes/validator-node.mdx, apps/nextra/pages/zh/network/nodes/validator-node.mdx
This pull request includes fixes and updates for three files: `resources.mdx`, `validator-node.mdx`, and `validator-node.md`. Below are the changes made:
1. **`resources.mdx`**:
- Fixed grammar: changed **"their own storage space"** to **"its own storage space"** for consistency with singular subject agreement.
- Improved clarity and consistency in descriptions of resource storage and API references.
2. **`validator-node.mdx`**:
- Corrected grammar: updated **"has been setup"** to **"has been set up"** for proper verb usage.
3. **`validator-node.md`**:
- Fixed a typo: corrected **"Valdiator"** to **"Validator"** in the Chinese title.
These changes ensure improved accuracy and clarity in documentation.
=> Fix typos and improve grammar in `resources.mdx`, `validator-node.mdx`, and `validator-node.md`

apps/nextra/pages/en/build/create-aptos-dapp/faq.mdx, apps/nextra/pages/en/build/sdks/dotnet-sdk/queries/view.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx
🎯 Overview
This pull request enhances the documentation's readability and professionalism by fixing grammatical issues and improving clarity across multiple files.
🔍 Detailed Changes
📁 apps/nextra/pages/en/build/create-aptos-dapp/faq.mdx
1️⃣ Removed Redundant Word
Old: without any incurring any runtime performance costs
New: without incurring any runtime performance costs
💡 Reason: Eliminated redundancy to improve readability
2️⃣ Fixed Number Agreement
Old: For detailed instruction
New: For detailed instructions
💡 Reason: Corrected plural form for better grammatical accuracy
📁 apps/nextra/pages/en/build/sdks/dotnet-sdk/queries/view.mdx
3️⃣ Corrected Technical Term
Old: without any types arguments
New: without any type arguments
💡 Reason: Fixed singular form for technical accuracy
4️⃣ …
=> 📝 Documentation Grammar and Clarity Improvements

apps/nextra/components/faucet/FaucetForm.tsx, apps/nextra/middleware.ts
Updates:
* hardcodes redirect from `/network/faucet/` to `/en/network/faucet/` (instead of auto-detecing locale) as page is only available in english (other locales will throw a 404)
* fixed error handling
=> Faucet page error handling and locale redirect

apps/nextra/components/faucet/index.tsx
Remove the github login option from the faucet until we figure out why it breaks
=> Remove github from faucet login for now

apps/nextra/pages/en/build/smart-contracts/object/using-objects.mdx
This PR updates the `Events` example under the Object section. 
- Introduced `LiquidityPool` struct which was missing.
- The function now uses `Metadata` object to get asset's address.
- Annotated `CreateLiquidtyPoolEvent` with `#[event]` attribute for clarity.
=> [using-objects] modify events example

apps/nextra/pages/en/build/smart-contracts/deployment.mdx
=> fix: Include type arguments for object transfer in cli example

apps/nextra/pages/en/network/blockchain/delegated-staking.mdx
Added Beneficiary entity to `delegated-staking.mdx` defining it as the operator-designated address for receiving commission rewards.
This addition is crucial for completeness and accuracy as Beneficiaries play a vital role in commission distribution within the delegation system. Without this documentation, operators and stakeholders lack clarity on how operator commissions are managed and distributed.
=> Add beneficiary to delegation pool entities

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/_meta.tsx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/create-processor.mdx
=> Creating a processor

apps/nextra/pages/en/build/smart-contracts/compiler_v2.mdx, packages/aptos-nextra-components/src/utils/mdast/mdast.test.ts
**This PR is ready for review, but it should only be merged in after releasing the aptos CLI v6.0.0.**
Compiler v2 will become the default when we release the CLI, and this PR makes doc changes corresponding to it.
The change in the file `packages/aptos-nextra-components/src/utils/mdast/mdast.test.ts` is a result of running `pnpm lint`.
=> Making compiler v2 default

apps/nextra/pages/en/build/smart-contracts/book/move-2.mdx
In Move 2, we report an error for unnecessary `acquires` even when the transitive call graph has a cycle (bug fix). We add this info to the release notes.
=> Add note about the acquires annotation bug fix

apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/define-schema.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/quickstart.mdx
=> Indexer PostgreSQL install instructions

apps/nextra/pages/en/network/nodes/configure.mdx, apps/nextra/pages/en/network/nodes/configure/_meta.tsx, apps/nextra/pages/en/network/nodes/configure/consensus-observer.mdx
This PR adds a new configuration page for consensus observer in the node section. You can see a preview [here](https://developer-docs-nextra-git-codetails-aptoslabs.vercel.app/en/network/nodes/configure/consensus-observer).
=> [Nodes] Add configuration guide for consensus observer

apps/nextra/pages/en/build/indexer/indexer-sdk/_meta.tsx, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/migration-guide.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/setup.mdx
=> Indexer SDK Migration Guide

apps/nextra/pages/en/build/sdks/wallet-adapter.mdx
=> [lychee] Fix broken link for aptosconnect

apps/nextra/pages/en/build/smart-contracts.mdx, apps/nextra/pages/en/build/smart-contracts/book/standard-library.mdx
1. Update link to std library documentation (to point to the correct page)
2. Update text about compiler v2 (no longer in early beta testing)
3. `pnpm fmt` or `pnpm lint` created changes for `mdast.test.ts`
=> Fix link to std library and update compiler v2 statement

apps/nextra/pages/en/network/nodes/validator-node/deploy-nodes/using-gcp.mdx
Updates a mistaken "AWS" to "GCP".
I also verified that the steps match the other set of working steps 1:1. https://github.com/aptos-labs/aptos-core/blob/main/terraform/aptos-node/gcp/README.md
=> Update GCP step typo

apps/nextra/pages/en/build/sdks/ts-sdk/account/account-abstraction.mdx
https://github.com/aptos-labs/aptos-ts-sdk/blob/85cfc416c5abdea312106562e21448719a52062b/src/api/transaction.ts#L351
```
async waitForTransaction(args: {
transactionHash: HexInput;
options?: WaitForTransactionOptions;
}): Promise<CommittedTransactionResponse> {
return waitForTransaction({
aptosConfig: this.config,
...args,
});
}
```
=> [AA] Fix parameter type error in the documentation

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/_meta.tsx, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/txn-importer.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/documentation/advanced-tutorials.mdx
- [x ] Have you ran `pnpm fmt`?
- [x ] Have you ran `pnpm lint`?
=> importing test transactions

README.md, apps/nextra/components/landing/sections/FooterSection.tsx, apps/nextra/pages/en/developer-platforms/contribute/examples/pairings.mdx, apps/nextra/pages/en/network/releases.mdx
Fix broken link and update installation instructions
- Fixed invalid GitHub actions URL by removing extra slash.
- Improved clarity in the setup steps.
- Minor formatting adjustments for better readability.
fix: update Twitter URL to x.com format
Updated the Twitter URL from https://twitter.com/ to https://x.com/ to reflect the platform's rebranding.
=> Fix broken link and update installation instructions

apps/nextra/pages/en/network/glossary.mdx
1. Adds section for "J" within Glossary
2. Move "J" below "I"
=> Address alphabetical ordering for "J" terms within Glossary

apps/nextra/pages/en/build/sdks/wallet-adapter/browser-extension-wallets.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/wallets.mdx, apps/nextra/pages/en/build/smart-contracts/book/functions.mdx
Entry functions allow more than what was previously documented.
Also includes fixes to satisfy the link checker.
Closes https://github.com/aptos-labs/aptos-core/issues/14571
=> Update documentation for entry functions

apps/nextra/pages/en/build/sdks/wallet-adapter/browser-extension-wallets.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx, apps/nextra/pages/en/build/sdks/wallet-adapter/wallets.mdx
Following https://github.com/aptos-labs/aptos-wallet-adapter/pull/464 , the new adapter version now only supports AIP-62 wallets (i.e no legacy plugin wallets)
=> Scope legacy plugin wallets to prior adapter versions

apps/nextra/pages/en/build/smart-contracts/book/functions.mdx
In the move-book, we showcase the receiver-style syntax for generic functions with an example.
=> [move-book] Showcase receiver style syntax for generic functions

README.md
Made updates to readme file to match my experience of getting it to work (ex: removed prebuild step which errors)
=> readme setup fixes

apps/nextra/pages/en/build/cli/running-a-local-network.mdx, apps/nextra/pages/en/network/nodes/bootstrap-fullnode/aptos-db-restore.mdx, apps/nextra/pages/en/network/nodes/localnet/local-development-network.mdx, apps/nextra/pages/zh/build/cli/running-a-local-network.mdx, apps/nextra/pages/zh/network/nodes/localnet/local-development-network.mdx
=> Update the increase to 'minimum RLIMIT_NOFILE requirement' in the dev docs

apps/nextra/public/scripts/install_cli.py
The `install_cli.py` script currently fetches the 24.04 version in all cases on Linux.
Urgent fix because this is breaking `internal-ops` workflows that download the CLI, as we're still on Ubuntu 22.04 in the CI environment.
=> Fetch Ubuntu 22.04 CLI when older OpenSSL detected

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/_meta.tsx, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/txn-importer.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/txn-script.mdx
=> generating test transactions with move script

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/_meta.tsx, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/processor-test.mdx
=> testing processor

apps/nextra/next.config.mjs, apps/nextra/pages/en/build/indexer/nft-aggregator.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces/topaz.mdx
- Marked Topaz as a deprecated marketplace
- Created a new "Deprecated Marketplaces" section in the marketplaces overview page
- Clarified that historical data for deprecated marketplaces is still maintained and accessible
=> add topaz back

apps/nextra/pages/en/build/cli/install-cli/install-cli-windows.mdx
Fix (python3 to python): user testing confirms that windows users will get an error if they run `python3 --version` even if they have a working version of python 3.6+ installed. This error causes beginner devs to suffer 5+ minutes of confusion and perhaps redundant installing.
=> Tippi fifestarr patch windows cli

apps/nextra/public/scripts/install_cli.ps1
The current script uses `exit 0` or `exit 1`, which can cause errors in PowerShell when running remote scripts using `iwr https://aptos.dev/scripts/install_cli.ps1 | iex`, or unexpectedly close the terminal during repeated installations — which can be confusing for developers.
**There are two possible solutions:**
1. Use `powershell -NoExit -Command "iwr https://aptos.dev/scripts/install_cli.ps1 | iex"` to prevent the terminal from exiting.
2. Modify the current script to use return instead of exit.
=> [install_cli] fix install_cli.ps1 windows exit

apps/nextra/pages/en/build/cli/install-cli/install-cli-linux.mdx, apps/nextra/pages/en/build/cli/install-cli/install-cli-mac.mdx, apps/nextra/pages/en/build/cli/install-cli/install-cli-windows.mdx
Python requires you to know how to first install Python, which then requires more work.  This lets you run everything with just the native shell tools available on every machine.
=> [cli] Add installation shell scripts rather than Python

apps/nextra/pages/en/build/smart-contracts/linter.mdx
Documentation for two new lint rules: `almost_swapped` and `self_assignment`
- If any existing pages were renamed or removed: N/A
=> [Linter] almost_swapped and self_assignment lint rules added to dev docs

apps/nextra/pages/en/build/indexer/nft-aggregator/marketplaces.mdx
Fixed marketplace link where it used to link to mdx 
tested locally
=> fix marketplace link

apps/nextra/pages/en/build/guides/exchanges.mdx
=> Update exchange guide with store deletion events

apps/nextra/pages/en/build/indexer/indexer-api/indexer-reference.mdx
=> [indexer] Update deprecated tables

apps/nextra/pages/en/build/cli/install-cli/install-cli-windows.mdx, apps/nextra/pages/zh/build/cli/install-cli/install-cli-windows.mdx
=> [Cli] Winget Install

apps/nextra/pages/en/build/sdks/wallet-adapter/x-chain-accounts.mdx
=> Add steps and wallets table

apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx, apps/nextra/pages/en/developer-platforms/contribute/components/image.mdx
=> Update docs for fetching wallets in the wallet adapter

apps/nextra/pages/en/build/smart-contracts/book/enums.mdx
=> [fix]  enums.mdx example code error

apps/nextra/pages/en/build/smart-contracts/book/variables.mdx
=> [fix] fix variables.mdx example code error

apps/nextra/pages/zh/build/create-aptos-dapp.mdx, apps/nextra/pages/zh/build/smart-contracts.mdx
=> [i18n] add zh smart-contracts / create-aptos-dapp

apps/nextra/pages/en/build/smart-contracts/maps.mdx
Resolves https://github.com/aptos-labs/developer-docs/issues/949
Fixes https://github.com/aptos-labs/developer-docs/issues/949
=> Fix typo in maps.mdx

.github/workflows/link-check.yml
=> [links] Ignore Google cloud link, works, but not through CI

apps/nextra/pages/en/build/sdks/wallet-adapter/dapp.mdx
=> Update wallet adapter instructions for dapps

apps/nextra/pages/en/build/guides/key-rotation.mdx, apps/nextra/pages/en/build/indexer/indexer-sdk/advanced-tutorials/processor-test.mdx
remove redundant word in comment
=> chore: remove redundant word in comment

apps/nextra/pages/en/build/guides/build-e2e-dapp/1-create-smart-contract.mdx, apps/nextra/pages/en/build/smart-contracts/maps.mdx
=> chore: fix some typos in comment

apps/nextra/pages/en/build/sdks/wallet-adapter.mdx
=> [wallet-adapter] Add OKX connect instructions

apps/nextra/pages/en/build/_meta.tsx, apps/nextra/pages/en/build/aips/_meta.tsx, apps/nextra/pages/en/build/aips/aip-115.mdx, apps/nextra/pages/en/build/aips/overview.mdx
=> [stateless] Add AIP FAQ for stateless

apps/nextra/pages/en/build/smart-contracts/linter.mdx
Added docs for new lint, this is a companion PR for [this one](https://github.com/aptos-labs/aptos-core/pull/16852).
=> [linter] Added equal_operands_in_bin_op docs

apps/nextra/pages/zh/build/smart-contracts/cryptography.mdx
Replaced the broken link to ../../network/blockchain/move.mdx with ../why-move.mdx in the Chinese cryptography.mdx. This directs users to the correct and existing Move introduction page in the zh docs, resolving a file not found error.
=> fix(zh/cryptography): update broken Move reference link to correct page

apps/nextra/pages/en/build/aips.mdx, apps/nextra/pages/en/build/aips/_meta.tsx, apps/nextra/pages/en/build/aips/aip-88.mdx
=> [aips] Add AIP-88 FAQ

.github/workflows/ci.yml
This PR introduces `pull_request_target` for the main CI build/lint job. It requires  permissions since there are some internal packages that are used in part of the build. The `permission-check` job ensures the permissions are locked down, and Semgrep enforces that job's existence. 
This PR is tested by #992 , which should be safe to land alongside it as long as Semgrep passes on it
=> [gha] allow external contributors build/lint

apps/nextra/pages/en/build/indexer/nft-aggregator.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/graphql-api.mdx, apps/nextra/pages/en/build/indexer/nft-aggregator/nft-aggregator-table.mdx
=> update nft aggregator doc
